// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hall_base/hall_base.proto

package hall_base

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ====================== 基础数据结构 ====================== //
type GameSvrInfo struct {
	Hostid               *int32   `protobuf:"varint,1,opt,name=hostid" json:"hostid,omitempty"`
	ListenPort           *int32   `protobuf:"varint,2,opt,name=listen_port,json=listenPort" json:"listen_port,omitempty"`
	Gameid               *int32   `protobuf:"varint,3,opt,name=gameid" json:"gameid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameSvrInfo) Reset()         { *m = GameSvrInfo{} }
func (m *GameSvrInfo) String() string { return proto.CompactTextString(m) }
func (*GameSvrInfo) ProtoMessage()    {}
func (*GameSvrInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{0}
}

func (m *GameSvrInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameSvrInfo.Unmarshal(m, b)
}
func (m *GameSvrInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameSvrInfo.Marshal(b, m, deterministic)
}
func (m *GameSvrInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameSvrInfo.Merge(m, src)
}
func (m *GameSvrInfo) XXX_Size() int {
	return xxx_messageInfo_GameSvrInfo.Size(m)
}
func (m *GameSvrInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GameSvrInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GameSvrInfo proto.InternalMessageInfo

func (m *GameSvrInfo) GetHostid() int32 {
	if m != nil && m.Hostid != nil {
		return *m.Hostid
	}
	return 0
}

func (m *GameSvrInfo) GetListenPort() int32 {
	if m != nil && m.ListenPort != nil {
		return *m.ListenPort
	}
	return 0
}

func (m *GameSvrInfo) GetGameid() int32 {
	if m != nil && m.Gameid != nil {
		return *m.Gameid
	}
	return 0
}

type GameUserPulse struct {
	Userid               *int32   `protobuf:"varint,1,opt,name=userid" json:"userid,omitempty"`
	Roomid               *int32   `protobuf:"varint,2,opt,name=roomid" json:"roomid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameUserPulse) Reset()         { *m = GameUserPulse{} }
func (m *GameUserPulse) String() string { return proto.CompactTextString(m) }
func (*GameUserPulse) ProtoMessage()    {}
func (*GameUserPulse) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{1}
}

func (m *GameUserPulse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameUserPulse.Unmarshal(m, b)
}
func (m *GameUserPulse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameUserPulse.Marshal(b, m, deterministic)
}
func (m *GameUserPulse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameUserPulse.Merge(m, src)
}
func (m *GameUserPulse) XXX_Size() int {
	return xxx_messageInfo_GameUserPulse.Size(m)
}
func (m *GameUserPulse) XXX_DiscardUnknown() {
	xxx_messageInfo_GameUserPulse.DiscardUnknown(m)
}

var xxx_messageInfo_GameUserPulse proto.InternalMessageInfo

func (m *GameUserPulse) GetUserid() int32 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *GameUserPulse) GetRoomid() int32 {
	if m != nil && m.Roomid != nil {
		return *m.Roomid
	}
	return 0
}

type AdditinalData struct {
	OriginalReq          *int32   `protobuf:"varint,1,opt,name=original_req,json=originalReq" json:"original_req,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	DataLen              *int32   `protobuf:"varint,3,opt,name=data_len,json=dataLen" json:"data_len,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdditinalData) Reset()         { *m = AdditinalData{} }
func (m *AdditinalData) String() string { return proto.CompactTextString(m) }
func (*AdditinalData) ProtoMessage()    {}
func (*AdditinalData) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{2}
}

func (m *AdditinalData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdditinalData.Unmarshal(m, b)
}
func (m *AdditinalData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdditinalData.Marshal(b, m, deterministic)
}
func (m *AdditinalData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdditinalData.Merge(m, src)
}
func (m *AdditinalData) XXX_Size() int {
	return xxx_messageInfo_AdditinalData.Size(m)
}
func (m *AdditinalData) XXX_DiscardUnknown() {
	xxx_messageInfo_AdditinalData.DiscardUnknown(m)
}

var xxx_messageInfo_AdditinalData proto.InternalMessageInfo

func (m *AdditinalData) GetOriginalReq() int32 {
	if m != nil && m.OriginalReq != nil {
		return *m.OriginalReq
	}
	return 0
}

func (m *AdditinalData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AdditinalData) GetDataLen() int32 {
	if m != nil && m.DataLen != nil {
		return *m.DataLen
	}
	return 0
}

// 客户端认证消息HR_CLIENT_VALID
type ValidClentReq struct {
	ClientType           *int32   `protobuf:"varint,1,opt,name=client_type,json=clientType" json:"client_type,omitempty"`
	Gameid               *int32   `protobuf:"varint,2,opt,name=gameid" json:"gameid,omitempty"`
	ListenPort           *int32   `protobuf:"varint,3,opt,name=listen_port,json=listenPort" json:"listen_port,omitempty"`
	Hostid               *int32   `protobuf:"varint,4,opt,name=hostid" json:"hostid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidClentReq) Reset()         { *m = ValidClentReq{} }
func (m *ValidClentReq) String() string { return proto.CompactTextString(m) }
func (*ValidClentReq) ProtoMessage()    {}
func (*ValidClentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{3}
}

func (m *ValidClentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidClentReq.Unmarshal(m, b)
}
func (m *ValidClentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidClentReq.Marshal(b, m, deterministic)
}
func (m *ValidClentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidClentReq.Merge(m, src)
}
func (m *ValidClentReq) XXX_Size() int {
	return xxx_messageInfo_ValidClentReq.Size(m)
}
func (m *ValidClentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidClentReq.DiscardUnknown(m)
}

var xxx_messageInfo_ValidClentReq proto.InternalMessageInfo

func (m *ValidClentReq) GetClientType() int32 {
	if m != nil && m.ClientType != nil {
		return *m.ClientType
	}
	return 0
}

func (m *ValidClentReq) GetGameid() int32 {
	if m != nil && m.Gameid != nil {
		return *m.Gameid
	}
	return 0
}

func (m *ValidClentReq) GetListenPort() int32 {
	if m != nil && m.ListenPort != nil {
		return *m.ListenPort
	}
	return 0
}

func (m *ValidClentReq) GetHostid() int32 {
	if m != nil && m.Hostid != nil {
		return *m.Hostid
	}
	return 0
}

type ValidClentResp struct {
	Code                 *int32   `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidClentResp) Reset()         { *m = ValidClentResp{} }
func (m *ValidClentResp) String() string { return proto.CompactTextString(m) }
func (*ValidClentResp) ProtoMessage()    {}
func (*ValidClentResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{4}
}

func (m *ValidClentResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidClentResp.Unmarshal(m, b)
}
func (m *ValidClentResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidClentResp.Marshal(b, m, deterministic)
}
func (m *ValidClentResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidClentResp.Merge(m, src)
}
func (m *ValidClentResp) XXX_Size() int {
	return xxx_messageInfo_ValidClentResp.Size(m)
}
func (m *ValidClentResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidClentResp.DiscardUnknown(m)
}

var xxx_messageInfo_ValidClentResp proto.InternalMessageInfo

func (m *ValidClentResp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

// 服务间心跳
type SvrPulse struct {
	TickCount            *int64   `protobuf:"varint,1,opt,name=tick_count,json=tickCount" json:"tick_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SvrPulse) Reset()         { *m = SvrPulse{} }
func (m *SvrPulse) String() string { return proto.CompactTextString(m) }
func (*SvrPulse) ProtoMessage()    {}
func (*SvrPulse) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{5}
}

func (m *SvrPulse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SvrPulse.Unmarshal(m, b)
}
func (m *SvrPulse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SvrPulse.Marshal(b, m, deterministic)
}
func (m *SvrPulse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SvrPulse.Merge(m, src)
}
func (m *SvrPulse) XXX_Size() int {
	return xxx_messageInfo_SvrPulse.Size(m)
}
func (m *SvrPulse) XXX_DiscardUnknown() {
	xxx_messageInfo_SvrPulse.DiscardUnknown(m)
}

var xxx_messageInfo_SvrPulse proto.InternalMessageInfo

func (m *SvrPulse) GetTickCount() int64 {
	if m != nil && m.TickCount != nil {
		return *m.TickCount
	}
	return 0
}

// 游戏服务心跳
type GamePulse struct {
	Gameid               *int32   `protobuf:"varint,1,opt,name=gameid" json:"gameid,omitempty"`
	TickCount            *int64   `protobuf:"varint,2,opt,name=tick_count,json=tickCount" json:"tick_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GamePulse) Reset()         { *m = GamePulse{} }
func (m *GamePulse) String() string { return proto.CompactTextString(m) }
func (*GamePulse) ProtoMessage()    {}
func (*GamePulse) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{6}
}

func (m *GamePulse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamePulse.Unmarshal(m, b)
}
func (m *GamePulse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamePulse.Marshal(b, m, deterministic)
}
func (m *GamePulse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamePulse.Merge(m, src)
}
func (m *GamePulse) XXX_Size() int {
	return xxx_messageInfo_GamePulse.Size(m)
}
func (m *GamePulse) XXX_DiscardUnknown() {
	xxx_messageInfo_GamePulse.DiscardUnknown(m)
}

var xxx_messageInfo_GamePulse proto.InternalMessageInfo

func (m *GamePulse) GetGameid() int32 {
	if m != nil && m.Gameid != nil {
		return *m.Gameid
	}
	return 0
}

func (m *GamePulse) GetTickCount() int64 {
	if m != nil && m.TickCount != nil {
		return *m.TickCount
	}
	return 0
}

type EnterGameReqV2 struct {
	Userid               *int32         `protobuf:"varint,1,opt,name=userid" json:"userid,omitempty"`
	Gameid               *int32         `protobuf:"varint,2,opt,name=gameid" json:"gameid,omitempty"`
	Roomid               *int32         `protobuf:"varint,3,opt,name=roomid" json:"roomid,omitempty"`
	Hardid               *string        `protobuf:"bytes,4,opt,name=hardid" json:"hardid,omitempty"`
	AdditinalData        *AdditinalData `protobuf:"bytes,5,opt,name=additinal_data,json=additinalData" json:"additinal_data,omitempty"`
	DepositType          *int32         `protobuf:"varint,6,opt,name=deposit_type,json=depositType" json:"deposit_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *EnterGameReqV2) Reset()         { *m = EnterGameReqV2{} }
func (m *EnterGameReqV2) String() string { return proto.CompactTextString(m) }
func (*EnterGameReqV2) ProtoMessage()    {}
func (*EnterGameReqV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{7}
}

func (m *EnterGameReqV2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterGameReqV2.Unmarshal(m, b)
}
func (m *EnterGameReqV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterGameReqV2.Marshal(b, m, deterministic)
}
func (m *EnterGameReqV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterGameReqV2.Merge(m, src)
}
func (m *EnterGameReqV2) XXX_Size() int {
	return xxx_messageInfo_EnterGameReqV2.Size(m)
}
func (m *EnterGameReqV2) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterGameReqV2.DiscardUnknown(m)
}

var xxx_messageInfo_EnterGameReqV2 proto.InternalMessageInfo

func (m *EnterGameReqV2) GetUserid() int32 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *EnterGameReqV2) GetGameid() int32 {
	if m != nil && m.Gameid != nil {
		return *m.Gameid
	}
	return 0
}

func (m *EnterGameReqV2) GetRoomid() int32 {
	if m != nil && m.Roomid != nil {
		return *m.Roomid
	}
	return 0
}

func (m *EnterGameReqV2) GetHardid() string {
	if m != nil && m.Hardid != nil {
		return *m.Hardid
	}
	return ""
}

func (m *EnterGameReqV2) GetAdditinalData() *AdditinalData {
	if m != nil {
		return m.AdditinalData
	}
	return nil
}

func (m *EnterGameReqV2) GetDepositType() int32 {
	if m != nil && m.DepositType != nil {
		return *m.DepositType
	}
	return 0
}

type EnterClubGameReqV2 struct {
	Userid               *int32         `protobuf:"varint,1,opt,name=userid" json:"userid,omitempty"`
	Gameid               *int32         `protobuf:"varint,2,opt,name=gameid" json:"gameid,omitempty"`
	Hardid               *string        `protobuf:"bytes,4,opt,name=hardid" json:"hardid,omitempty"`
	AdditinalData        *AdditinalData `protobuf:"bytes,5,opt,name=additinal_data,json=additinalData" json:"additinal_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *EnterClubGameReqV2) Reset()         { *m = EnterClubGameReqV2{} }
func (m *EnterClubGameReqV2) String() string { return proto.CompactTextString(m) }
func (*EnterClubGameReqV2) ProtoMessage()    {}
func (*EnterClubGameReqV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{8}
}

func (m *EnterClubGameReqV2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterClubGameReqV2.Unmarshal(m, b)
}
func (m *EnterClubGameReqV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterClubGameReqV2.Marshal(b, m, deterministic)
}
func (m *EnterClubGameReqV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterClubGameReqV2.Merge(m, src)
}
func (m *EnterClubGameReqV2) XXX_Size() int {
	return xxx_messageInfo_EnterClubGameReqV2.Size(m)
}
func (m *EnterClubGameReqV2) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterClubGameReqV2.DiscardUnknown(m)
}

var xxx_messageInfo_EnterClubGameReqV2 proto.InternalMessageInfo

func (m *EnterClubGameReqV2) GetUserid() int32 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *EnterClubGameReqV2) GetGameid() int32 {
	if m != nil && m.Gameid != nil {
		return *m.Gameid
	}
	return 0
}

func (m *EnterClubGameReqV2) GetHardid() string {
	if m != nil && m.Hardid != nil {
		return *m.Hardid
	}
	return ""
}

func (m *EnterClubGameReqV2) GetAdditinalData() *AdditinalData {
	if m != nil {
		return m.AdditinalData
	}
	return nil
}

// 进游戏成功通知
type EnterGameOkNotify struct {
	Userid               *int32   `protobuf:"varint,1,opt,name=userid" json:"userid,omitempty"`
	Gameid               *int32   `protobuf:"varint,2,opt,name=gameid" json:"gameid,omitempty"`
	Roomid               *int32   `protobuf:"varint,3,opt,name=roomid" json:"roomid,omitempty"`
	Tableno              *int64   `protobuf:"varint,4,opt,name=tableno" json:"tableno,omitempty"`
	Chairno              *int32   `protobuf:"varint,5,opt,name=chairno" json:"chairno,omitempty"`
	Areaid               *int32   `protobuf:"varint,6,opt,name=areaid" json:"areaid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterGameOkNotify) Reset()         { *m = EnterGameOkNotify{} }
func (m *EnterGameOkNotify) String() string { return proto.CompactTextString(m) }
func (*EnterGameOkNotify) ProtoMessage()    {}
func (*EnterGameOkNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{9}
}

func (m *EnterGameOkNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterGameOkNotify.Unmarshal(m, b)
}
func (m *EnterGameOkNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterGameOkNotify.Marshal(b, m, deterministic)
}
func (m *EnterGameOkNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterGameOkNotify.Merge(m, src)
}
func (m *EnterGameOkNotify) XXX_Size() int {
	return xxx_messageInfo_EnterGameOkNotify.Size(m)
}
func (m *EnterGameOkNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterGameOkNotify.DiscardUnknown(m)
}

var xxx_messageInfo_EnterGameOkNotify proto.InternalMessageInfo

func (m *EnterGameOkNotify) GetUserid() int32 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *EnterGameOkNotify) GetGameid() int32 {
	if m != nil && m.Gameid != nil {
		return *m.Gameid
	}
	return 0
}

func (m *EnterGameOkNotify) GetRoomid() int32 {
	if m != nil && m.Roomid != nil {
		return *m.Roomid
	}
	return 0
}

func (m *EnterGameOkNotify) GetTableno() int64 {
	if m != nil && m.Tableno != nil {
		return *m.Tableno
	}
	return 0
}

func (m *EnterGameOkNotify) GetChairno() int32 {
	if m != nil && m.Chairno != nil {
		return *m.Chairno
	}
	return 0
}

func (m *EnterGameOkNotify) GetAreaid() int32 {
	if m != nil && m.Areaid != nil {
		return *m.Areaid
	}
	return 0
}

// 进游戏成功通知
type LeaveGameNotify struct {
	Userid               *int32   `protobuf:"varint,1,opt,name=userid" json:"userid,omitempty"`
	Gameid               *int32   `protobuf:"varint,2,opt,name=gameid" json:"gameid,omitempty"`
	Roomid               *int32   `protobuf:"varint,3,opt,name=roomid" json:"roomid,omitempty"`
	Tableno              *int64   `protobuf:"varint,4,opt,name=tableno" json:"tableno,omitempty"`
	Chairno              *int32   `protobuf:"varint,5,opt,name=chairno" json:"chairno,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveGameNotify) Reset()         { *m = LeaveGameNotify{} }
func (m *LeaveGameNotify) String() string { return proto.CompactTextString(m) }
func (*LeaveGameNotify) ProtoMessage()    {}
func (*LeaveGameNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{10}
}

func (m *LeaveGameNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveGameNotify.Unmarshal(m, b)
}
func (m *LeaveGameNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveGameNotify.Marshal(b, m, deterministic)
}
func (m *LeaveGameNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveGameNotify.Merge(m, src)
}
func (m *LeaveGameNotify) XXX_Size() int {
	return xxx_messageInfo_LeaveGameNotify.Size(m)
}
func (m *LeaveGameNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveGameNotify.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveGameNotify proto.InternalMessageInfo

func (m *LeaveGameNotify) GetUserid() int32 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *LeaveGameNotify) GetGameid() int32 {
	if m != nil && m.Gameid != nil {
		return *m.Gameid
	}
	return 0
}

func (m *LeaveGameNotify) GetRoomid() int32 {
	if m != nil && m.Roomid != nil {
		return *m.Roomid
	}
	return 0
}

func (m *LeaveGameNotify) GetTableno() int64 {
	if m != nil && m.Tableno != nil {
		return *m.Tableno
	}
	return 0
}

func (m *LeaveGameNotify) GetChairno() int32 {
	if m != nil && m.Chairno != nil {
		return *m.Chairno
	}
	return 0
}

// 游戏服务内玩家心跳
type GameUsersPulse struct {
	GameSvr              *GameSvrInfo     `protobuf:"bytes,1,opt,name=game_svr,json=gameSvr" json:"game_svr,omitempty"`
	UsersPulse           []*GameUserPulse `protobuf:"bytes,2,rep,name=users_pulse,json=usersPulse" json:"users_pulse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GameUsersPulse) Reset()         { *m = GameUsersPulse{} }
func (m *GameUsersPulse) String() string { return proto.CompactTextString(m) }
func (*GameUsersPulse) ProtoMessage()    {}
func (*GameUsersPulse) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{11}
}

func (m *GameUsersPulse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameUsersPulse.Unmarshal(m, b)
}
func (m *GameUsersPulse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameUsersPulse.Marshal(b, m, deterministic)
}
func (m *GameUsersPulse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameUsersPulse.Merge(m, src)
}
func (m *GameUsersPulse) XXX_Size() int {
	return xxx_messageInfo_GameUsersPulse.Size(m)
}
func (m *GameUsersPulse) XXX_DiscardUnknown() {
	xxx_messageInfo_GameUsersPulse.DiscardUnknown(m)
}

var xxx_messageInfo_GameUsersPulse proto.InternalMessageInfo

func (m *GameUsersPulse) GetGameSvr() *GameSvrInfo {
	if m != nil {
		return m.GameSvr
	}
	return nil
}

func (m *GameUsersPulse) GetUsersPulse() []*GameUserPulse {
	if m != nil {
		return m.UsersPulse
	}
	return nil
}

// 游戏服务内玩家数量
type RoomUserCount struct {
	Roomid               *int32   `protobuf:"varint,1,opt,name=roomid" json:"roomid,omitempty"`
	Areaid               *int32   `protobuf:"varint,2,opt,name=areaid" json:"areaid,omitempty"`
	Usercount            *int32   `protobuf:"varint,3,opt,name=usercount" json:"usercount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomUserCount) Reset()         { *m = RoomUserCount{} }
func (m *RoomUserCount) String() string { return proto.CompactTextString(m) }
func (*RoomUserCount) ProtoMessage()    {}
func (*RoomUserCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{12}
}

func (m *RoomUserCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomUserCount.Unmarshal(m, b)
}
func (m *RoomUserCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomUserCount.Marshal(b, m, deterministic)
}
func (m *RoomUserCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomUserCount.Merge(m, src)
}
func (m *RoomUserCount) XXX_Size() int {
	return xxx_messageInfo_RoomUserCount.Size(m)
}
func (m *RoomUserCount) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomUserCount.DiscardUnknown(m)
}

var xxx_messageInfo_RoomUserCount proto.InternalMessageInfo

func (m *RoomUserCount) GetRoomid() int32 {
	if m != nil && m.Roomid != nil {
		return *m.Roomid
	}
	return 0
}

func (m *RoomUserCount) GetAreaid() int32 {
	if m != nil && m.Areaid != nil {
		return *m.Areaid
	}
	return 0
}

func (m *RoomUserCount) GetUsercount() int32 {
	if m != nil && m.Usercount != nil {
		return *m.Usercount
	}
	return 0
}

type GameUserCount struct {
	Gameid               *int32           `protobuf:"varint,1,opt,name=gameid" json:"gameid,omitempty"`
	RoomUsercount        []*RoomUserCount `protobuf:"bytes,2,rep,name=room_usercount,json=roomUsercount" json:"room_usercount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GameUserCount) Reset()         { *m = GameUserCount{} }
func (m *GameUserCount) String() string { return proto.CompactTextString(m) }
func (*GameUserCount) ProtoMessage()    {}
func (*GameUserCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{13}
}

func (m *GameUserCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameUserCount.Unmarshal(m, b)
}
func (m *GameUserCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameUserCount.Marshal(b, m, deterministic)
}
func (m *GameUserCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameUserCount.Merge(m, src)
}
func (m *GameUserCount) XXX_Size() int {
	return xxx_messageInfo_GameUserCount.Size(m)
}
func (m *GameUserCount) XXX_DiscardUnknown() {
	xxx_messageInfo_GameUserCount.DiscardUnknown(m)
}

var xxx_messageInfo_GameUserCount proto.InternalMessageInfo

func (m *GameUserCount) GetGameid() int32 {
	if m != nil && m.Gameid != nil {
		return *m.Gameid
	}
	return 0
}

func (m *GameUserCount) GetRoomUsercount() []*RoomUserCount {
	if m != nil {
		return m.RoomUsercount
	}
	return nil
}

// 游戏开始通知
type StartGameNotify struct {
	Gameid               *int32   `protobuf:"varint,1,opt,name=gameid" json:"gameid,omitempty"`
	Roomid               *int32   `protobuf:"varint,2,opt,name=roomid" json:"roomid,omitempty"`
	Tableno              *int64   `protobuf:"varint,3,opt,name=tableno" json:"tableno,omitempty"`
	Userid               []int32  `protobuf:"varint,4,rep,name=userid" json:"userid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartGameNotify) Reset()         { *m = StartGameNotify{} }
func (m *StartGameNotify) String() string { return proto.CompactTextString(m) }
func (*StartGameNotify) ProtoMessage()    {}
func (*StartGameNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{14}
}

func (m *StartGameNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartGameNotify.Unmarshal(m, b)
}
func (m *StartGameNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartGameNotify.Marshal(b, m, deterministic)
}
func (m *StartGameNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartGameNotify.Merge(m, src)
}
func (m *StartGameNotify) XXX_Size() int {
	return xxx_messageInfo_StartGameNotify.Size(m)
}
func (m *StartGameNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_StartGameNotify.DiscardUnknown(m)
}

var xxx_messageInfo_StartGameNotify proto.InternalMessageInfo

func (m *StartGameNotify) GetGameid() int32 {
	if m != nil && m.Gameid != nil {
		return *m.Gameid
	}
	return 0
}

func (m *StartGameNotify) GetRoomid() int32 {
	if m != nil && m.Roomid != nil {
		return *m.Roomid
	}
	return 0
}

func (m *StartGameNotify) GetTableno() int64 {
	if m != nil && m.Tableno != nil {
		return *m.Tableno
	}
	return 0
}

func (m *StartGameNotify) GetUserid() []int32 {
	if m != nil {
		return m.Userid
	}
	return nil
}

// 结算
type UserGameResult struct {
	Userid               *int32   `protobuf:"varint,1,opt,name=userid" json:"userid,omitempty"`
	Chairno              *int32   `protobuf:"varint,2,opt,name=chairno" json:"chairno,omitempty"`
	BaseDeposit          *int64   `protobuf:"varint,3,opt,name=base_deposit,json=baseDeposit" json:"base_deposit,omitempty"`
	OldDeposit           *int64   `protobuf:"varint,4,opt,name=old_deposit,json=oldDeposit" json:"old_deposit,omitempty"`
	DiffDeposit          *int64   `protobuf:"varint,5,opt,name=diff_deposit,json=diffDeposit" json:"diff_deposit,omitempty"`
	Cut                  *int64   `protobuf:"varint,6,opt,name=cut" json:"cut,omitempty"`
	Fee                  *int64   `protobuf:"varint,7,opt,name=fee" json:"fee,omitempty"`
	Extra                *int64   `protobuf:"varint,8,opt,name=extra" json:"extra,omitempty"`
	Timecost             *int32   `protobuf:"varint,9,opt,name=timecost" json:"timecost,omitempty"`
	BoutCount            *int32   `protobuf:"varint,10,opt,name=bout_count,json=boutCount" json:"bout_count,omitempty"`
	WinCount             *int32   `protobuf:"varint,11,opt,name=win_count,json=winCount" json:"win_count,omitempty"`
	LossCount            *int32   `protobuf:"varint,12,opt,name=loss_count,json=lossCount" json:"loss_count,omitempty"`
	StandoffCount        *int32   `protobuf:"varint,13,opt,name=standoff_count,json=standoffCount" json:"standoff_count,omitempty"`
	OfflineCount         *int32   `protobuf:"varint,14,opt,name=offline_count,json=offlineCount" json:"offline_count,omitempty"`
	Experience           *int32   `protobuf:"varint,15,opt,name=experience" json:"experience,omitempty"`
	Playerlevel          *int32   `protobuf:"varint,16,opt,name=playerlevel" json:"playerlevel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGameResult) Reset()         { *m = UserGameResult{} }
func (m *UserGameResult) String() string { return proto.CompactTextString(m) }
func (*UserGameResult) ProtoMessage()    {}
func (*UserGameResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{15}
}

func (m *UserGameResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGameResult.Unmarshal(m, b)
}
func (m *UserGameResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGameResult.Marshal(b, m, deterministic)
}
func (m *UserGameResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGameResult.Merge(m, src)
}
func (m *UserGameResult) XXX_Size() int {
	return xxx_messageInfo_UserGameResult.Size(m)
}
func (m *UserGameResult) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGameResult.DiscardUnknown(m)
}

var xxx_messageInfo_UserGameResult proto.InternalMessageInfo

func (m *UserGameResult) GetUserid() int32 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *UserGameResult) GetChairno() int32 {
	if m != nil && m.Chairno != nil {
		return *m.Chairno
	}
	return 0
}

func (m *UserGameResult) GetBaseDeposit() int64 {
	if m != nil && m.BaseDeposit != nil {
		return *m.BaseDeposit
	}
	return 0
}

func (m *UserGameResult) GetOldDeposit() int64 {
	if m != nil && m.OldDeposit != nil {
		return *m.OldDeposit
	}
	return 0
}

func (m *UserGameResult) GetDiffDeposit() int64 {
	if m != nil && m.DiffDeposit != nil {
		return *m.DiffDeposit
	}
	return 0
}

func (m *UserGameResult) GetCut() int64 {
	if m != nil && m.Cut != nil {
		return *m.Cut
	}
	return 0
}

func (m *UserGameResult) GetFee() int64 {
	if m != nil && m.Fee != nil {
		return *m.Fee
	}
	return 0
}

func (m *UserGameResult) GetExtra() int64 {
	if m != nil && m.Extra != nil {
		return *m.Extra
	}
	return 0
}

func (m *UserGameResult) GetTimecost() int32 {
	if m != nil && m.Timecost != nil {
		return *m.Timecost
	}
	return 0
}

func (m *UserGameResult) GetBoutCount() int32 {
	if m != nil && m.BoutCount != nil {
		return *m.BoutCount
	}
	return 0
}

func (m *UserGameResult) GetWinCount() int32 {
	if m != nil && m.WinCount != nil {
		return *m.WinCount
	}
	return 0
}

func (m *UserGameResult) GetLossCount() int32 {
	if m != nil && m.LossCount != nil {
		return *m.LossCount
	}
	return 0
}

func (m *UserGameResult) GetStandoffCount() int32 {
	if m != nil && m.StandoffCount != nil {
		return *m.StandoffCount
	}
	return 0
}

func (m *UserGameResult) GetOfflineCount() int32 {
	if m != nil && m.OfflineCount != nil {
		return *m.OfflineCount
	}
	return 0
}

func (m *UserGameResult) GetExperience() int32 {
	if m != nil && m.Experience != nil {
		return *m.Experience
	}
	return 0
}

func (m *UserGameResult) GetPlayerlevel() int32 {
	if m != nil && m.Playerlevel != nil {
		return *m.Playerlevel
	}
	return 0
}

type RefreshGameResult struct {
	Roomid               *int32            `protobuf:"varint,1,opt,name=roomid" json:"roomid,omitempty"`
	Tableno              *int64            `protobuf:"varint,2,opt,name=tableno" json:"tableno,omitempty"`
	Flag                 *int32            `protobuf:"varint,3,opt,name=flag" json:"flag,omitempty"`
	UserResult           []*UserGameResult `protobuf:"bytes,4,rep,name=user_result,json=userResult" json:"user_result,omitempty"`
	Gameid               *int32            `protobuf:"varint,5,opt,name=gameid" json:"gameid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RefreshGameResult) Reset()         { *m = RefreshGameResult{} }
func (m *RefreshGameResult) String() string { return proto.CompactTextString(m) }
func (*RefreshGameResult) ProtoMessage()    {}
func (*RefreshGameResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{16}
}

func (m *RefreshGameResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshGameResult.Unmarshal(m, b)
}
func (m *RefreshGameResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshGameResult.Marshal(b, m, deterministic)
}
func (m *RefreshGameResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshGameResult.Merge(m, src)
}
func (m *RefreshGameResult) XXX_Size() int {
	return xxx_messageInfo_RefreshGameResult.Size(m)
}
func (m *RefreshGameResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshGameResult.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshGameResult proto.InternalMessageInfo

func (m *RefreshGameResult) GetRoomid() int32 {
	if m != nil && m.Roomid != nil {
		return *m.Roomid
	}
	return 0
}

func (m *RefreshGameResult) GetTableno() int64 {
	if m != nil && m.Tableno != nil {
		return *m.Tableno
	}
	return 0
}

func (m *RefreshGameResult) GetFlag() int32 {
	if m != nil && m.Flag != nil {
		return *m.Flag
	}
	return 0
}

func (m *RefreshGameResult) GetUserResult() []*UserGameResult {
	if m != nil {
		return m.UserResult
	}
	return nil
}

func (m *RefreshGameResult) GetGameid() int32 {
	if m != nil && m.Gameid != nil {
		return *m.Gameid
	}
	return 0
}

// 房间断线通知
type RoomOfflineNotify struct {
	Hostid               *int32   `protobuf:"varint,1,opt,name=hostid" json:"hostid,omitempty"`
	Port                 *int32   `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	Roomid               []int32  `protobuf:"varint,3,rep,name=roomid" json:"roomid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomOfflineNotify) Reset()         { *m = RoomOfflineNotify{} }
func (m *RoomOfflineNotify) String() string { return proto.CompactTextString(m) }
func (*RoomOfflineNotify) ProtoMessage()    {}
func (*RoomOfflineNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{17}
}

func (m *RoomOfflineNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomOfflineNotify.Unmarshal(m, b)
}
func (m *RoomOfflineNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomOfflineNotify.Marshal(b, m, deterministic)
}
func (m *RoomOfflineNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomOfflineNotify.Merge(m, src)
}
func (m *RoomOfflineNotify) XXX_Size() int {
	return xxx_messageInfo_RoomOfflineNotify.Size(m)
}
func (m *RoomOfflineNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomOfflineNotify.DiscardUnknown(m)
}

var xxx_messageInfo_RoomOfflineNotify proto.InternalMessageInfo

func (m *RoomOfflineNotify) GetHostid() int32 {
	if m != nil && m.Hostid != nil {
		return *m.Hostid
	}
	return 0
}

func (m *RoomOfflineNotify) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *RoomOfflineNotify) GetRoomid() []int32 {
	if m != nil {
		return m.Roomid
	}
	return nil
}

//========HTTP通用结构==========//
type HttpHead struct {
	Field                *string  `protobuf:"bytes,1,opt,name=field" json:"field,omitempty"`
	Value                *string  `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HttpHead) Reset()         { *m = HttpHead{} }
func (m *HttpHead) String() string { return proto.CompactTextString(m) }
func (*HttpHead) ProtoMessage()    {}
func (*HttpHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{18}
}

func (m *HttpHead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpHead.Unmarshal(m, b)
}
func (m *HttpHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpHead.Marshal(b, m, deterministic)
}
func (m *HttpHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpHead.Merge(m, src)
}
func (m *HttpHead) XXX_Size() int {
	return xxx_messageInfo_HttpHead.Size(m)
}
func (m *HttpHead) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpHead.DiscardUnknown(m)
}

var xxx_messageInfo_HttpHead proto.InternalMessageInfo

func (m *HttpHead) GetField() string {
	if m != nil && m.Field != nil {
		return *m.Field
	}
	return ""
}

func (m *HttpHead) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type HttpReq struct {
	Sendtype             *int32      `protobuf:"varint,1,opt,name=sendtype" json:"sendtype,omitempty"`
	Heads                []*HttpHead `protobuf:"bytes,2,rep,name=heads" json:"heads,omitempty"`
	Body                 *string     `protobuf:"bytes,3,opt,name=body" json:"body,omitempty"`
	Url                  *string     `protobuf:"bytes,4,opt,name=url" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *HttpReq) Reset()         { *m = HttpReq{} }
func (m *HttpReq) String() string { return proto.CompactTextString(m) }
func (*HttpReq) ProtoMessage()    {}
func (*HttpReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{19}
}

func (m *HttpReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpReq.Unmarshal(m, b)
}
func (m *HttpReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpReq.Marshal(b, m, deterministic)
}
func (m *HttpReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpReq.Merge(m, src)
}
func (m *HttpReq) XXX_Size() int {
	return xxx_messageInfo_HttpReq.Size(m)
}
func (m *HttpReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpReq.DiscardUnknown(m)
}

var xxx_messageInfo_HttpReq proto.InternalMessageInfo

func (m *HttpReq) GetSendtype() int32 {
	if m != nil && m.Sendtype != nil {
		return *m.Sendtype
	}
	return 0
}

func (m *HttpReq) GetHeads() []*HttpHead {
	if m != nil {
		return m.Heads
	}
	return nil
}

func (m *HttpReq) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

func (m *HttpReq) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

type HttpResp struct {
	Code                 *int32   `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Data                 *string  `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HttpResp) Reset()         { *m = HttpResp{} }
func (m *HttpResp) String() string { return proto.CompactTextString(m) }
func (*HttpResp) ProtoMessage()    {}
func (*HttpResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{20}
}

func (m *HttpResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpResp.Unmarshal(m, b)
}
func (m *HttpResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpResp.Marshal(b, m, deterministic)
}
func (m *HttpResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpResp.Merge(m, src)
}
func (m *HttpResp) XXX_Size() int {
	return xxx_messageInfo_HttpResp.Size(m)
}
func (m *HttpResp) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpResp.DiscardUnknown(m)
}

var xxx_messageInfo_HttpResp proto.InternalMessageInfo

func (m *HttpResp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *HttpResp) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

// 事件上报通知
type EventReportNotify struct {
	Url                  *string  `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Body                 *string  `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
	Sendtype             *int32   `protobuf:"varint,3,opt,name=sendtype" json:"sendtype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventReportNotify) Reset()         { *m = EventReportNotify{} }
func (m *EventReportNotify) String() string { return proto.CompactTextString(m) }
func (*EventReportNotify) ProtoMessage()    {}
func (*EventReportNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{21}
}

func (m *EventReportNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventReportNotify.Unmarshal(m, b)
}
func (m *EventReportNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventReportNotify.Marshal(b, m, deterministic)
}
func (m *EventReportNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventReportNotify.Merge(m, src)
}
func (m *EventReportNotify) XXX_Size() int {
	return xxx_messageInfo_EventReportNotify.Size(m)
}
func (m *EventReportNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_EventReportNotify.DiscardUnknown(m)
}

var xxx_messageInfo_EventReportNotify proto.InternalMessageInfo

func (m *EventReportNotify) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *EventReportNotify) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

func (m *EventReportNotify) GetSendtype() int32 {
	if m != nil && m.Sendtype != nil {
		return *m.Sendtype
	}
	return 0
}

//========来自HallSvr的请求=======//
// 通过硬件信息登录注册
type LogonRegisterReq struct {
	Channelid            *int32   `protobuf:"varint,1,opt,name=channelid" json:"channelid,omitempty"`
	Appid                *int32   `protobuf:"varint,2,opt,name=appid" json:"appid,omitempty"`
	EncryptDeviceid      *string  `protobuf:"bytes,3,opt,name=encrypt_deviceid,json=encryptDeviceid" json:"encrypt_deviceid,omitempty"`
	Hardid               *string  `protobuf:"bytes,4,opt,name=hardid" json:"hardid,omitempty"`
	EncryptHardid        *string  `protobuf:"bytes,5,opt,name=encrypt_hardid,json=encryptHardid" json:"encrypt_hardid,omitempty"`
	Systemid             *string  `protobuf:"bytes,6,opt,name=systemid" json:"systemid,omitempty"`
	EncryptSystemid      *string  `protobuf:"bytes,7,opt,name=encrypt_systemid,json=encryptSystemid" json:"encrypt_systemid,omitempty"`
	Imei                 *string  `protobuf:"bytes,8,opt,name=imei" json:"imei,omitempty"`
	EncryptImei          *string  `protobuf:"bytes,9,opt,name=encrypt_imei,json=encryptImei" json:"encrypt_imei,omitempty"`
	EncryptImsi          *string  `protobuf:"bytes,10,opt,name=encrypt_imsi,json=encryptImsi" json:"encrypt_imsi,omitempty"`
	EncryptSimSerial     *string  `protobuf:"bytes,11,opt,name=encrypt_sim_serial,json=encryptSimSerial" json:"encrypt_sim_serial,omitempty"`
	VerifyCode           *string  `protobuf:"bytes,12,opt,name=verify_code,json=verifyCode" json:"verify_code,omitempty"`
	DownloadGroup        *int32   `protobuf:"varint,13,opt,name=download_group,json=downloadGroup" json:"download_group,omitempty"`
	OsName               *int32   `protobuf:"varint,14,opt,name=os_name,json=osName" json:"os_name,omitempty"`
	ClientIp             *string  `protobuf:"bytes,15,opt,name=client_ip,json=clientIp" json:"client_ip,omitempty"`
	Gameid               *int32   `protobuf:"varint,16,opt,name=gameid" json:"gameid,omitempty"`
	HallGroup            *int32   `protobuf:"varint,17,opt,name=hall_group,json=hallGroup" json:"hall_group,omitempty"`
	Deviceid             *string  `protobuf:"bytes,18,opt,name=deviceid" json:"deviceid,omitempty"`
	HeadUrl              *string  `protobuf:"bytes,19,opt,name=head_url,json=headUrl" json:"head_url,omitempty"`
	Brand                *string  `protobuf:"bytes,51,opt,name=brand" json:"brand,omitempty"`
	ModelNo              *string  `protobuf:"bytes,52,opt,name=model_no,json=modelNo" json:"model_no,omitempty"`
	SysLangue            *string  `protobuf:"bytes,53,opt,name=sys_langue,json=sysLangue" json:"sys_langue,omitempty"`
	AppLangue            *string  `protobuf:"bytes,54,opt,name=app_langue,json=appLangue" json:"app_langue,omitempty"`
	NetType              *int32   `protobuf:"varint,57,opt,name=net_type,json=netType" json:"net_type,omitempty"`
	MobileCarriers       *string  `protobuf:"bytes,58,opt,name=mobile_carriers,json=mobileCarriers" json:"mobile_carriers,omitempty"`
	Os                   *int32   `protobuf:"varint,59,opt,name=os" json:"os,omitempty"`
	OsVer                *string  `protobuf:"bytes,60,opt,name=os_ver,json=osVer" json:"os_ver,omitempty"`
	MaingameId           *int32   `protobuf:"varint,61,opt,name=maingame_id,json=maingameId" json:"maingame_id,omitempty"`
	HallVer              *string  `protobuf:"bytes,62,opt,name=hall_ver,json=hallVer" json:"hall_ver,omitempty"`
	ResolutionX          *int32   `protobuf:"varint,63,opt,name=resolution_x,json=resolutionX" json:"resolution_x,omitempty"`
	ResolutionY          *int32   `protobuf:"varint,64,opt,name=resolution_y,json=resolutionY" json:"resolution_y,omitempty"`
	MaingameVer          *string  `protobuf:"bytes,65,opt,name=maingame_ver,json=maingameVer" json:"maingame_ver,omitempty"`
	Utm                  *string  `protobuf:"bytes,81,opt,name=utm" json:"utm,omitempty"`
	Recommenderid        *string  `protobuf:"bytes,82,opt,name=recommenderid" json:"recommenderid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogonRegisterReq) Reset()         { *m = LogonRegisterReq{} }
func (m *LogonRegisterReq) String() string { return proto.CompactTextString(m) }
func (*LogonRegisterReq) ProtoMessage()    {}
func (*LogonRegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{22}
}

func (m *LogonRegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogonRegisterReq.Unmarshal(m, b)
}
func (m *LogonRegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogonRegisterReq.Marshal(b, m, deterministic)
}
func (m *LogonRegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogonRegisterReq.Merge(m, src)
}
func (m *LogonRegisterReq) XXX_Size() int {
	return xxx_messageInfo_LogonRegisterReq.Size(m)
}
func (m *LogonRegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LogonRegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_LogonRegisterReq proto.InternalMessageInfo

func (m *LogonRegisterReq) GetChannelid() int32 {
	if m != nil && m.Channelid != nil {
		return *m.Channelid
	}
	return 0
}

func (m *LogonRegisterReq) GetAppid() int32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

func (m *LogonRegisterReq) GetEncryptDeviceid() string {
	if m != nil && m.EncryptDeviceid != nil {
		return *m.EncryptDeviceid
	}
	return ""
}

func (m *LogonRegisterReq) GetHardid() string {
	if m != nil && m.Hardid != nil {
		return *m.Hardid
	}
	return ""
}

func (m *LogonRegisterReq) GetEncryptHardid() string {
	if m != nil && m.EncryptHardid != nil {
		return *m.EncryptHardid
	}
	return ""
}

func (m *LogonRegisterReq) GetSystemid() string {
	if m != nil && m.Systemid != nil {
		return *m.Systemid
	}
	return ""
}

func (m *LogonRegisterReq) GetEncryptSystemid() string {
	if m != nil && m.EncryptSystemid != nil {
		return *m.EncryptSystemid
	}
	return ""
}

func (m *LogonRegisterReq) GetImei() string {
	if m != nil && m.Imei != nil {
		return *m.Imei
	}
	return ""
}

func (m *LogonRegisterReq) GetEncryptImei() string {
	if m != nil && m.EncryptImei != nil {
		return *m.EncryptImei
	}
	return ""
}

func (m *LogonRegisterReq) GetEncryptImsi() string {
	if m != nil && m.EncryptImsi != nil {
		return *m.EncryptImsi
	}
	return ""
}

func (m *LogonRegisterReq) GetEncryptSimSerial() string {
	if m != nil && m.EncryptSimSerial != nil {
		return *m.EncryptSimSerial
	}
	return ""
}

func (m *LogonRegisterReq) GetVerifyCode() string {
	if m != nil && m.VerifyCode != nil {
		return *m.VerifyCode
	}
	return ""
}

func (m *LogonRegisterReq) GetDownloadGroup() int32 {
	if m != nil && m.DownloadGroup != nil {
		return *m.DownloadGroup
	}
	return 0
}

func (m *LogonRegisterReq) GetOsName() int32 {
	if m != nil && m.OsName != nil {
		return *m.OsName
	}
	return 0
}

func (m *LogonRegisterReq) GetClientIp() string {
	if m != nil && m.ClientIp != nil {
		return *m.ClientIp
	}
	return ""
}

func (m *LogonRegisterReq) GetGameid() int32 {
	if m != nil && m.Gameid != nil {
		return *m.Gameid
	}
	return 0
}

func (m *LogonRegisterReq) GetHallGroup() int32 {
	if m != nil && m.HallGroup != nil {
		return *m.HallGroup
	}
	return 0
}

func (m *LogonRegisterReq) GetDeviceid() string {
	if m != nil && m.Deviceid != nil {
		return *m.Deviceid
	}
	return ""
}

func (m *LogonRegisterReq) GetHeadUrl() string {
	if m != nil && m.HeadUrl != nil {
		return *m.HeadUrl
	}
	return ""
}

func (m *LogonRegisterReq) GetBrand() string {
	if m != nil && m.Brand != nil {
		return *m.Brand
	}
	return ""
}

func (m *LogonRegisterReq) GetModelNo() string {
	if m != nil && m.ModelNo != nil {
		return *m.ModelNo
	}
	return ""
}

func (m *LogonRegisterReq) GetSysLangue() string {
	if m != nil && m.SysLangue != nil {
		return *m.SysLangue
	}
	return ""
}

func (m *LogonRegisterReq) GetAppLangue() string {
	if m != nil && m.AppLangue != nil {
		return *m.AppLangue
	}
	return ""
}

func (m *LogonRegisterReq) GetNetType() int32 {
	if m != nil && m.NetType != nil {
		return *m.NetType
	}
	return 0
}

func (m *LogonRegisterReq) GetMobileCarriers() string {
	if m != nil && m.MobileCarriers != nil {
		return *m.MobileCarriers
	}
	return ""
}

func (m *LogonRegisterReq) GetOs() int32 {
	if m != nil && m.Os != nil {
		return *m.Os
	}
	return 0
}

func (m *LogonRegisterReq) GetOsVer() string {
	if m != nil && m.OsVer != nil {
		return *m.OsVer
	}
	return ""
}

func (m *LogonRegisterReq) GetMaingameId() int32 {
	if m != nil && m.MaingameId != nil {
		return *m.MaingameId
	}
	return 0
}

func (m *LogonRegisterReq) GetHallVer() string {
	if m != nil && m.HallVer != nil {
		return *m.HallVer
	}
	return ""
}

func (m *LogonRegisterReq) GetResolutionX() int32 {
	if m != nil && m.ResolutionX != nil {
		return *m.ResolutionX
	}
	return 0
}

func (m *LogonRegisterReq) GetResolutionY() int32 {
	if m != nil && m.ResolutionY != nil {
		return *m.ResolutionY
	}
	return 0
}

func (m *LogonRegisterReq) GetMaingameVer() string {
	if m != nil && m.MaingameVer != nil {
		return *m.MaingameVer
	}
	return ""
}

func (m *LogonRegisterReq) GetUtm() string {
	if m != nil && m.Utm != nil {
		return *m.Utm
	}
	return ""
}

func (m *LogonRegisterReq) GetRecommenderid() string {
	if m != nil && m.Recommenderid != nil {
		return *m.Recommenderid
	}
	return ""
}

type LogonRegisterResp struct {
	Code                 *int32   `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	ThirdPartCode        *int32   `protobuf:"varint,2,opt,name=third_part_code,json=thirdPartCode" json:"third_part_code,omitempty"`
	Userid               *int32   `protobuf:"varint,3,opt,name=userid" json:"userid,omitempty"`
	UserType             *int32   `protobuf:"varint,4,opt,name=user_type,json=userType" json:"user_type,omitempty"`
	NickName             *string  `protobuf:"bytes,5,opt,name=nick_name,json=nickName" json:"nick_name,omitempty"`
	HeadUrl              *string  `protobuf:"bytes,6,opt,name=head_url,json=headUrl" json:"head_url,omitempty"`
	AcessToken           *string  `protobuf:"bytes,7,opt,name=acess_token,json=acessToken" json:"acess_token,omitempty"`
	LoginToken           *string  `protobuf:"bytes,8,opt,name=login_token,json=loginToken" json:"login_token,omitempty"`
	Uniqueid             *string  `protobuf:"bytes,9,opt,name=uniqueid" json:"uniqueid,omitempty"`
	NewUserFlag          *int32   `protobuf:"varint,10,opt,name=new_user_flag,json=newUserFlag" json:"new_user_flag,omitempty"`
	Deposit              *int64   `protobuf:"varint,11,opt,name=deposit" json:"deposit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogonRegisterResp) Reset()         { *m = LogonRegisterResp{} }
func (m *LogonRegisterResp) String() string { return proto.CompactTextString(m) }
func (*LogonRegisterResp) ProtoMessage()    {}
func (*LogonRegisterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{23}
}

func (m *LogonRegisterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogonRegisterResp.Unmarshal(m, b)
}
func (m *LogonRegisterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogonRegisterResp.Marshal(b, m, deterministic)
}
func (m *LogonRegisterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogonRegisterResp.Merge(m, src)
}
func (m *LogonRegisterResp) XXX_Size() int {
	return xxx_messageInfo_LogonRegisterResp.Size(m)
}
func (m *LogonRegisterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LogonRegisterResp.DiscardUnknown(m)
}

var xxx_messageInfo_LogonRegisterResp proto.InternalMessageInfo

func (m *LogonRegisterResp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *LogonRegisterResp) GetThirdPartCode() int32 {
	if m != nil && m.ThirdPartCode != nil {
		return *m.ThirdPartCode
	}
	return 0
}

func (m *LogonRegisterResp) GetUserid() int32 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *LogonRegisterResp) GetUserType() int32 {
	if m != nil && m.UserType != nil {
		return *m.UserType
	}
	return 0
}

func (m *LogonRegisterResp) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *LogonRegisterResp) GetHeadUrl() string {
	if m != nil && m.HeadUrl != nil {
		return *m.HeadUrl
	}
	return ""
}

func (m *LogonRegisterResp) GetAcessToken() string {
	if m != nil && m.AcessToken != nil {
		return *m.AcessToken
	}
	return ""
}

func (m *LogonRegisterResp) GetLoginToken() string {
	if m != nil && m.LoginToken != nil {
		return *m.LoginToken
	}
	return ""
}

func (m *LogonRegisterResp) GetUniqueid() string {
	if m != nil && m.Uniqueid != nil {
		return *m.Uniqueid
	}
	return ""
}

func (m *LogonRegisterResp) GetNewUserFlag() int32 {
	if m != nil && m.NewUserFlag != nil {
		return *m.NewUserFlag
	}
	return 0
}

func (m *LogonRegisterResp) GetDeposit() int64 {
	if m != nil && m.Deposit != nil {
		return *m.Deposit
	}
	return 0
}

// 登录
type LogonReq struct {
	Userid         *int32  `protobuf:"varint,1,opt,name=userid" json:"userid,omitempty"`
	Password       *string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Hardid         *string `protobuf:"bytes,3,opt,name=hardid" json:"hardid,omitempty"`
	Systemid       *string `protobuf:"bytes,4,opt,name=systemid" json:"systemid,omitempty"`
	Imei           *string `protobuf:"bytes,5,opt,name=imei" json:"imei,omitempty"`
	Deviceid       *string `protobuf:"bytes,6,opt,name=deviceid" json:"deviceid,omitempty"`
	Gameid         *int32  `protobuf:"varint,7,opt,name=gameid" json:"gameid,omitempty"`
	Channelid      *int32  `protobuf:"varint,8,opt,name=channelid" json:"channelid,omitempty"`
	Groupid        *int32  `protobuf:"varint,9,opt,name=groupid" json:"groupid,omitempty"`
	Hallsvrid      *int32  `protobuf:"varint,10,opt,name=hallsvrid" json:"hallsvrid,omitempty"`
	Flag           *int32  `protobuf:"varint,11,opt,name=flag" json:"flag,omitempty"`
	ClientIp       *string `protobuf:"bytes,12,opt,name=client_ip,json=clientIp" json:"client_ip,omitempty"`
	LogonInterval  *int32  `protobuf:"varint,13,opt,name=logon_interval,json=logonInterval" json:"logon_interval,omitempty"`
	Tokenid        *int32  `protobuf:"varint,14,opt,name=tokenid" json:"tokenid,omitempty"`
	Blocksvrid     *int32  `protobuf:"varint,15,opt,name=blocksvrid" json:"blocksvrid,omitempty"`
	Brand          *string `protobuf:"bytes,51,opt,name=brand" json:"brand,omitempty"`
	ModelNo        *string `protobuf:"bytes,52,opt,name=model_no,json=modelNo" json:"model_no,omitempty"`
	SysLangue      *string `protobuf:"bytes,53,opt,name=sys_langue,json=sysLangue" json:"sys_langue,omitempty"`
	AppLangue      *string `protobuf:"bytes,54,opt,name=app_langue,json=appLangue" json:"app_langue,omitempty"`
	NetType        *int32  `protobuf:"varint,57,opt,name=net_type,json=netType" json:"net_type,omitempty"`
	MobileCarriers *string `protobuf:"bytes,58,opt,name=mobile_carriers,json=mobileCarriers" json:"mobile_carriers,omitempty"`
	Os             *int32  `protobuf:"varint,59,opt,name=os" json:"os,omitempty"`
	OsVer          *string `protobuf:"bytes,60,opt,name=os_ver,json=osVer" json:"os_ver,omitempty"`
	MaingameId     *int32  `protobuf:"varint,61,opt,name=maingame_id,json=maingameId" json:"maingame_id,omitempty"`
	HallVer        *string `protobuf:"bytes,62,opt,name=hall_ver,json=hallVer" json:"hall_ver,omitempty"`
	ResolutionX    *int32  `protobuf:"varint,63,opt,name=resolution_x,json=resolutionX" json:"resolution_x,omitempty"`
	ResolutionY    *int32  `protobuf:"varint,64,opt,name=resolution_y,json=resolutionY" json:"resolution_y,omitempty"`
	LogonType      *int32  `protobuf:"varint,65,opt,name=logon_type,json=logonType" json:"logon_type,omitempty"`
	// 在合集大厅中触发的登陆，上报maingame_ver； 在游戏中触发的登陆，上报currentgame_ver
	MaingameVer          *string  `protobuf:"bytes,66,opt,name=maingame_ver,json=maingameVer" json:"maingame_ver,omitempty"`
	CurrentgameVer       *string  `protobuf:"bytes,67,opt,name=currentgame_ver,json=currentgameVer" json:"currentgame_ver,omitempty"`
	GameChannelid        *int32   `protobuf:"varint,68,opt,name=game_channelid,json=gameChannelid" json:"game_channelid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogonReq) Reset()         { *m = LogonReq{} }
func (m *LogonReq) String() string { return proto.CompactTextString(m) }
func (*LogonReq) ProtoMessage()    {}
func (*LogonReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{24}
}

func (m *LogonReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogonReq.Unmarshal(m, b)
}
func (m *LogonReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogonReq.Marshal(b, m, deterministic)
}
func (m *LogonReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogonReq.Merge(m, src)
}
func (m *LogonReq) XXX_Size() int {
	return xxx_messageInfo_LogonReq.Size(m)
}
func (m *LogonReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LogonReq.DiscardUnknown(m)
}

var xxx_messageInfo_LogonReq proto.InternalMessageInfo

func (m *LogonReq) GetUserid() int32 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *LogonReq) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *LogonReq) GetHardid() string {
	if m != nil && m.Hardid != nil {
		return *m.Hardid
	}
	return ""
}

func (m *LogonReq) GetSystemid() string {
	if m != nil && m.Systemid != nil {
		return *m.Systemid
	}
	return ""
}

func (m *LogonReq) GetImei() string {
	if m != nil && m.Imei != nil {
		return *m.Imei
	}
	return ""
}

func (m *LogonReq) GetDeviceid() string {
	if m != nil && m.Deviceid != nil {
		return *m.Deviceid
	}
	return ""
}

func (m *LogonReq) GetGameid() int32 {
	if m != nil && m.Gameid != nil {
		return *m.Gameid
	}
	return 0
}

func (m *LogonReq) GetChannelid() int32 {
	if m != nil && m.Channelid != nil {
		return *m.Channelid
	}
	return 0
}

func (m *LogonReq) GetGroupid() int32 {
	if m != nil && m.Groupid != nil {
		return *m.Groupid
	}
	return 0
}

func (m *LogonReq) GetHallsvrid() int32 {
	if m != nil && m.Hallsvrid != nil {
		return *m.Hallsvrid
	}
	return 0
}

func (m *LogonReq) GetFlag() int32 {
	if m != nil && m.Flag != nil {
		return *m.Flag
	}
	return 0
}

func (m *LogonReq) GetClientIp() string {
	if m != nil && m.ClientIp != nil {
		return *m.ClientIp
	}
	return ""
}

func (m *LogonReq) GetLogonInterval() int32 {
	if m != nil && m.LogonInterval != nil {
		return *m.LogonInterval
	}
	return 0
}

func (m *LogonReq) GetTokenid() int32 {
	if m != nil && m.Tokenid != nil {
		return *m.Tokenid
	}
	return 0
}

func (m *LogonReq) GetBlocksvrid() int32 {
	if m != nil && m.Blocksvrid != nil {
		return *m.Blocksvrid
	}
	return 0
}

func (m *LogonReq) GetBrand() string {
	if m != nil && m.Brand != nil {
		return *m.Brand
	}
	return ""
}

func (m *LogonReq) GetModelNo() string {
	if m != nil && m.ModelNo != nil {
		return *m.ModelNo
	}
	return ""
}

func (m *LogonReq) GetSysLangue() string {
	if m != nil && m.SysLangue != nil {
		return *m.SysLangue
	}
	return ""
}

func (m *LogonReq) GetAppLangue() string {
	if m != nil && m.AppLangue != nil {
		return *m.AppLangue
	}
	return ""
}

func (m *LogonReq) GetNetType() int32 {
	if m != nil && m.NetType != nil {
		return *m.NetType
	}
	return 0
}

func (m *LogonReq) GetMobileCarriers() string {
	if m != nil && m.MobileCarriers != nil {
		return *m.MobileCarriers
	}
	return ""
}

func (m *LogonReq) GetOs() int32 {
	if m != nil && m.Os != nil {
		return *m.Os
	}
	return 0
}

func (m *LogonReq) GetOsVer() string {
	if m != nil && m.OsVer != nil {
		return *m.OsVer
	}
	return ""
}

func (m *LogonReq) GetMaingameId() int32 {
	if m != nil && m.MaingameId != nil {
		return *m.MaingameId
	}
	return 0
}

func (m *LogonReq) GetHallVer() string {
	if m != nil && m.HallVer != nil {
		return *m.HallVer
	}
	return ""
}

func (m *LogonReq) GetResolutionX() int32 {
	if m != nil && m.ResolutionX != nil {
		return *m.ResolutionX
	}
	return 0
}

func (m *LogonReq) GetResolutionY() int32 {
	if m != nil && m.ResolutionY != nil {
		return *m.ResolutionY
	}
	return 0
}

func (m *LogonReq) GetLogonType() int32 {
	if m != nil && m.LogonType != nil {
		return *m.LogonType
	}
	return 0
}

func (m *LogonReq) GetMaingameVer() string {
	if m != nil && m.MaingameVer != nil {
		return *m.MaingameVer
	}
	return ""
}

func (m *LogonReq) GetCurrentgameVer() string {
	if m != nil && m.CurrentgameVer != nil {
		return *m.CurrentgameVer
	}
	return ""
}

func (m *LogonReq) GetGameChannelid() int32 {
	if m != nil && m.GameChannelid != nil {
		return *m.GameChannelid
	}
	return 0
}

type LogonResp struct {
	Code                 *int32   `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Userid               *int32   `protobuf:"varint,2,opt,name=userid" json:"userid,omitempty"`
	UserType             *int32   `protobuf:"varint,3,opt,name=user_type,json=userType" json:"user_type,omitempty"`
	NickName             *string  `protobuf:"bytes,4,opt,name=nick_name,json=nickName" json:"nick_name,omitempty"`
	HeadUrl              *string  `protobuf:"bytes,5,opt,name=head_url,json=headUrl" json:"head_url,omitempty"`
	AcessToken           *string  `protobuf:"bytes,6,opt,name=acess_token,json=acessToken" json:"acess_token,omitempty"`
	Uniqueid             *string  `protobuf:"bytes,7,opt,name=uniqueid" json:"uniqueid,omitempty"`
	Sex                  *int32   `protobuf:"varint,8,opt,name=sex" json:"sex,omitempty"`
	Deposit              *int64   `protobuf:"varint,9,opt,name=deposit" json:"deposit,omitempty"`
	Groupid              *int32   `protobuf:"varint,10,opt,name=groupid" json:"groupid,omitempty"`
	Flag                 *int32   `protobuf:"varint,11,opt,name=flag" json:"flag,omitempty"`
	Hardid               *string  `protobuf:"bytes,12,opt,name=hardid" json:"hardid,omitempty"`
	Timestamp            *int64   `protobuf:"varint,13,opt,name=timestamp" json:"timestamp,omitempty"`
	Handphone            *string  `protobuf:"bytes,14,opt,name=handphone" json:"handphone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogonResp) Reset()         { *m = LogonResp{} }
func (m *LogonResp) String() string { return proto.CompactTextString(m) }
func (*LogonResp) ProtoMessage()    {}
func (*LogonResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{25}
}

func (m *LogonResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogonResp.Unmarshal(m, b)
}
func (m *LogonResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogonResp.Marshal(b, m, deterministic)
}
func (m *LogonResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogonResp.Merge(m, src)
}
func (m *LogonResp) XXX_Size() int {
	return xxx_messageInfo_LogonResp.Size(m)
}
func (m *LogonResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LogonResp.DiscardUnknown(m)
}

var xxx_messageInfo_LogonResp proto.InternalMessageInfo

func (m *LogonResp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *LogonResp) GetUserid() int32 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *LogonResp) GetUserType() int32 {
	if m != nil && m.UserType != nil {
		return *m.UserType
	}
	return 0
}

func (m *LogonResp) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *LogonResp) GetHeadUrl() string {
	if m != nil && m.HeadUrl != nil {
		return *m.HeadUrl
	}
	return ""
}

func (m *LogonResp) GetAcessToken() string {
	if m != nil && m.AcessToken != nil {
		return *m.AcessToken
	}
	return ""
}

func (m *LogonResp) GetUniqueid() string {
	if m != nil && m.Uniqueid != nil {
		return *m.Uniqueid
	}
	return ""
}

func (m *LogonResp) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *LogonResp) GetDeposit() int64 {
	if m != nil && m.Deposit != nil {
		return *m.Deposit
	}
	return 0
}

func (m *LogonResp) GetGroupid() int32 {
	if m != nil && m.Groupid != nil {
		return *m.Groupid
	}
	return 0
}

func (m *LogonResp) GetFlag() int32 {
	if m != nil && m.Flag != nil {
		return *m.Flag
	}
	return 0
}

func (m *LogonResp) GetHardid() string {
	if m != nil && m.Hardid != nil {
		return *m.Hardid
	}
	return ""
}

func (m *LogonResp) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *LogonResp) GetHandphone() string {
	if m != nil && m.Handphone != nil {
		return *m.Handphone
	}
	return ""
}

// 登录成功通知
type LogonOkNotify struct {
	LogonReq             *LogonReq  `protobuf:"bytes,1,opt,name=logon_req,json=logonReq" json:"logon_req,omitempty"`
	LogonResp            *LogonResp `protobuf:"bytes,2,opt,name=logon_resp,json=logonResp" json:"logon_resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LogonOkNotify) Reset()         { *m = LogonOkNotify{} }
func (m *LogonOkNotify) String() string { return proto.CompactTextString(m) }
func (*LogonOkNotify) ProtoMessage()    {}
func (*LogonOkNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{26}
}

func (m *LogonOkNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogonOkNotify.Unmarshal(m, b)
}
func (m *LogonOkNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogonOkNotify.Marshal(b, m, deterministic)
}
func (m *LogonOkNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogonOkNotify.Merge(m, src)
}
func (m *LogonOkNotify) XXX_Size() int {
	return xxx_messageInfo_LogonOkNotify.Size(m)
}
func (m *LogonOkNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_LogonOkNotify.DiscardUnknown(m)
}

var xxx_messageInfo_LogonOkNotify proto.InternalMessageInfo

func (m *LogonOkNotify) GetLogonReq() *LogonReq {
	if m != nil {
		return m.LogonReq
	}
	return nil
}

func (m *LogonOkNotify) GetLogonResp() *LogonResp {
	if m != nil {
		return m.LogonResp
	}
	return nil
}

// 获取玩家游戏内信息
type QueryUserGameInfoReq struct {
	TargetUserid         *int32   `protobuf:"varint,1,opt,name=target_userid,json=targetUserid" json:"target_userid,omitempty"`
	MyUserid             *int32   `protobuf:"varint,2,opt,name=my_userid,json=myUserid" json:"my_userid,omitempty"`
	Gameid               *int32   `protobuf:"varint,3,opt,name=gameid" json:"gameid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryUserGameInfoReq) Reset()         { *m = QueryUserGameInfoReq{} }
func (m *QueryUserGameInfoReq) String() string { return proto.CompactTextString(m) }
func (*QueryUserGameInfoReq) ProtoMessage()    {}
func (*QueryUserGameInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{27}
}

func (m *QueryUserGameInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUserGameInfoReq.Unmarshal(m, b)
}
func (m *QueryUserGameInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUserGameInfoReq.Marshal(b, m, deterministic)
}
func (m *QueryUserGameInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserGameInfoReq.Merge(m, src)
}
func (m *QueryUserGameInfoReq) XXX_Size() int {
	return xxx_messageInfo_QueryUserGameInfoReq.Size(m)
}
func (m *QueryUserGameInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserGameInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserGameInfoReq proto.InternalMessageInfo

func (m *QueryUserGameInfoReq) GetTargetUserid() int32 {
	if m != nil && m.TargetUserid != nil {
		return *m.TargetUserid
	}
	return 0
}

func (m *QueryUserGameInfoReq) GetMyUserid() int32 {
	if m != nil && m.MyUserid != nil {
		return *m.MyUserid
	}
	return 0
}

func (m *QueryUserGameInfoReq) GetGameid() int32 {
	if m != nil && m.Gameid != nil {
		return *m.Gameid
	}
	return 0
}

type QueryUserGameInfoResp struct {
	Code                 *int32   `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	TotalBout            *int32   `protobuf:"varint,2,opt,name=total_bout,json=totalBout" json:"total_bout,omitempty"`
	WinBout              *int32   `protobuf:"varint,3,opt,name=win_bout,json=winBout" json:"win_bout,omitempty"`
	LossBout             *int32   `protobuf:"varint,4,opt,name=loss_bout,json=lossBout" json:"loss_bout,omitempty"`
	StandoffBout         *int32   `protobuf:"varint,5,opt,name=standoff_bout,json=standoffBout" json:"standoff_bout,omitempty"`
	Experience           *int32   `protobuf:"varint,6,opt,name=experience" json:"experience,omitempty"`
	Score                *int32   `protobuf:"varint,7,opt,name=score" json:"score,omitempty"`
	TimeCost             *int32   `protobuf:"varint,8,opt,name=time_cost,json=timeCost" json:"time_cost,omitempty"`
	Playerlevel          *int32   `protobuf:"varint,9,opt,name=playerlevel" json:"playerlevel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryUserGameInfoResp) Reset()         { *m = QueryUserGameInfoResp{} }
func (m *QueryUserGameInfoResp) String() string { return proto.CompactTextString(m) }
func (*QueryUserGameInfoResp) ProtoMessage()    {}
func (*QueryUserGameInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{28}
}

func (m *QueryUserGameInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUserGameInfoResp.Unmarshal(m, b)
}
func (m *QueryUserGameInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUserGameInfoResp.Marshal(b, m, deterministic)
}
func (m *QueryUserGameInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserGameInfoResp.Merge(m, src)
}
func (m *QueryUserGameInfoResp) XXX_Size() int {
	return xxx_messageInfo_QueryUserGameInfoResp.Size(m)
}
func (m *QueryUserGameInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserGameInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserGameInfoResp proto.InternalMessageInfo

func (m *QueryUserGameInfoResp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *QueryUserGameInfoResp) GetTotalBout() int32 {
	if m != nil && m.TotalBout != nil {
		return *m.TotalBout
	}
	return 0
}

func (m *QueryUserGameInfoResp) GetWinBout() int32 {
	if m != nil && m.WinBout != nil {
		return *m.WinBout
	}
	return 0
}

func (m *QueryUserGameInfoResp) GetLossBout() int32 {
	if m != nil && m.LossBout != nil {
		return *m.LossBout
	}
	return 0
}

func (m *QueryUserGameInfoResp) GetStandoffBout() int32 {
	if m != nil && m.StandoffBout != nil {
		return *m.StandoffBout
	}
	return 0
}

func (m *QueryUserGameInfoResp) GetExperience() int32 {
	if m != nil && m.Experience != nil {
		return *m.Experience
	}
	return 0
}

func (m *QueryUserGameInfoResp) GetScore() int32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *QueryUserGameInfoResp) GetTimeCost() int32 {
	if m != nil && m.TimeCost != nil {
		return *m.TimeCost
	}
	return 0
}

func (m *QueryUserGameInfoResp) GetPlayerlevel() int32 {
	if m != nil && m.Playerlevel != nil {
		return *m.Playerlevel
	}
	return 0
}

// 批量获取用户在游戏内的信息
type QueryUsersGameInfoReq struct {
	Gameid               *int32   `protobuf:"varint,1,opt,name=gameid" json:"gameid,omitempty"`
	Userids              []int32  `protobuf:"varint,2,rep,name=userids" json:"userids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryUsersGameInfoReq) Reset()         { *m = QueryUsersGameInfoReq{} }
func (m *QueryUsersGameInfoReq) String() string { return proto.CompactTextString(m) }
func (*QueryUsersGameInfoReq) ProtoMessage()    {}
func (*QueryUsersGameInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{29}
}

func (m *QueryUsersGameInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUsersGameInfoReq.Unmarshal(m, b)
}
func (m *QueryUsersGameInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUsersGameInfoReq.Marshal(b, m, deterministic)
}
func (m *QueryUsersGameInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUsersGameInfoReq.Merge(m, src)
}
func (m *QueryUsersGameInfoReq) XXX_Size() int {
	return xxx_messageInfo_QueryUsersGameInfoReq.Size(m)
}
func (m *QueryUsersGameInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUsersGameInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUsersGameInfoReq proto.InternalMessageInfo

func (m *QueryUsersGameInfoReq) GetGameid() int32 {
	if m != nil && m.Gameid != nil {
		return *m.Gameid
	}
	return 0
}

func (m *QueryUsersGameInfoReq) GetUserids() []int32 {
	if m != nil {
		return m.Userids
	}
	return nil
}

type UserGameInfo struct {
	Userid               *int32   `protobuf:"varint,1,opt,name=userid" json:"userid,omitempty"`
	Level                *int32   `protobuf:"varint,2,opt,name=level" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGameInfo) Reset()         { *m = UserGameInfo{} }
func (m *UserGameInfo) String() string { return proto.CompactTextString(m) }
func (*UserGameInfo) ProtoMessage()    {}
func (*UserGameInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{30}
}

func (m *UserGameInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGameInfo.Unmarshal(m, b)
}
func (m *UserGameInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGameInfo.Marshal(b, m, deterministic)
}
func (m *UserGameInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGameInfo.Merge(m, src)
}
func (m *UserGameInfo) XXX_Size() int {
	return xxx_messageInfo_UserGameInfo.Size(m)
}
func (m *UserGameInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGameInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserGameInfo proto.InternalMessageInfo

func (m *UserGameInfo) GetUserid() int32 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *UserGameInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

type QueryUsersGameInfoResp struct {
	Code                 *int32          `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Usersinfo            []*UserGameInfo `protobuf:"bytes,2,rep,name=usersinfo" json:"usersinfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *QueryUsersGameInfoResp) Reset()         { *m = QueryUsersGameInfoResp{} }
func (m *QueryUsersGameInfoResp) String() string { return proto.CompactTextString(m) }
func (*QueryUsersGameInfoResp) ProtoMessage()    {}
func (*QueryUsersGameInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{31}
}

func (m *QueryUsersGameInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUsersGameInfoResp.Unmarshal(m, b)
}
func (m *QueryUsersGameInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUsersGameInfoResp.Marshal(b, m, deterministic)
}
func (m *QueryUsersGameInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUsersGameInfoResp.Merge(m, src)
}
func (m *QueryUsersGameInfoResp) XXX_Size() int {
	return xxx_messageInfo_QueryUsersGameInfoResp.Size(m)
}
func (m *QueryUsersGameInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUsersGameInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUsersGameInfoResp proto.InternalMessageInfo

func (m *QueryUsersGameInfoResp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *QueryUsersGameInfoResp) GetUsersinfo() []*UserGameInfo {
	if m != nil {
		return m.Usersinfo
	}
	return nil
}

// 检查是否可用
type CheckPlaceValidReq struct {
	Userid               *int32   `protobuf:"varint,1,opt,name=userid" json:"userid,omitempty"`
	Channelid            *int32   `protobuf:"varint,2,opt,name=channelid" json:"channelid,omitempty"`
	Lat                  *string  `protobuf:"bytes,3,opt,name=lat" json:"lat,omitempty"`
	Lon                  *string  `protobuf:"bytes,4,opt,name=lon" json:"lon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckPlaceValidReq) Reset()         { *m = CheckPlaceValidReq{} }
func (m *CheckPlaceValidReq) String() string { return proto.CompactTextString(m) }
func (*CheckPlaceValidReq) ProtoMessage()    {}
func (*CheckPlaceValidReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{32}
}

func (m *CheckPlaceValidReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckPlaceValidReq.Unmarshal(m, b)
}
func (m *CheckPlaceValidReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckPlaceValidReq.Marshal(b, m, deterministic)
}
func (m *CheckPlaceValidReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckPlaceValidReq.Merge(m, src)
}
func (m *CheckPlaceValidReq) XXX_Size() int {
	return xxx_messageInfo_CheckPlaceValidReq.Size(m)
}
func (m *CheckPlaceValidReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckPlaceValidReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckPlaceValidReq proto.InternalMessageInfo

func (m *CheckPlaceValidReq) GetUserid() int32 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *CheckPlaceValidReq) GetChannelid() int32 {
	if m != nil && m.Channelid != nil {
		return *m.Channelid
	}
	return 0
}

func (m *CheckPlaceValidReq) GetLat() string {
	if m != nil && m.Lat != nil {
		return *m.Lat
	}
	return ""
}

func (m *CheckPlaceValidReq) GetLon() string {
	if m != nil && m.Lon != nil {
		return *m.Lon
	}
	return ""
}

type CheckPlaceValidResp struct {
	Code                 *int32   `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckPlaceValidResp) Reset()         { *m = CheckPlaceValidResp{} }
func (m *CheckPlaceValidResp) String() string { return proto.CompactTextString(m) }
func (*CheckPlaceValidResp) ProtoMessage()    {}
func (*CheckPlaceValidResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_80b3503d5242968b, []int{33}
}

func (m *CheckPlaceValidResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckPlaceValidResp.Unmarshal(m, b)
}
func (m *CheckPlaceValidResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckPlaceValidResp.Marshal(b, m, deterministic)
}
func (m *CheckPlaceValidResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckPlaceValidResp.Merge(m, src)
}
func (m *CheckPlaceValidResp) XXX_Size() int {
	return xxx_messageInfo_CheckPlaceValidResp.Size(m)
}
func (m *CheckPlaceValidResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckPlaceValidResp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckPlaceValidResp proto.InternalMessageInfo

func (m *CheckPlaceValidResp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*GameSvrInfo)(nil), "hall.base.GameSvrInfo")
	proto.RegisterType((*GameUserPulse)(nil), "hall.base.GameUserPulse")
	proto.RegisterType((*AdditinalData)(nil), "hall.base.AdditinalData")
	proto.RegisterType((*ValidClentReq)(nil), "hall.base.ValidClentReq")
	proto.RegisterType((*ValidClentResp)(nil), "hall.base.ValidClentResp")
	proto.RegisterType((*SvrPulse)(nil), "hall.base.SvrPulse")
	proto.RegisterType((*GamePulse)(nil), "hall.base.GamePulse")
	proto.RegisterType((*EnterGameReqV2)(nil), "hall.base.EnterGameReqV2")
	proto.RegisterType((*EnterClubGameReqV2)(nil), "hall.base.EnterClubGameReqV2")
	proto.RegisterType((*EnterGameOkNotify)(nil), "hall.base.EnterGameOkNotify")
	proto.RegisterType((*LeaveGameNotify)(nil), "hall.base.LeaveGameNotify")
	proto.RegisterType((*GameUsersPulse)(nil), "hall.base.GameUsersPulse")
	proto.RegisterType((*RoomUserCount)(nil), "hall.base.RoomUserCount")
	proto.RegisterType((*GameUserCount)(nil), "hall.base.GameUserCount")
	proto.RegisterType((*StartGameNotify)(nil), "hall.base.StartGameNotify")
	proto.RegisterType((*UserGameResult)(nil), "hall.base.UserGameResult")
	proto.RegisterType((*RefreshGameResult)(nil), "hall.base.RefreshGameResult")
	proto.RegisterType((*RoomOfflineNotify)(nil), "hall.base.RoomOfflineNotify")
	proto.RegisterType((*HttpHead)(nil), "hall.base.HttpHead")
	proto.RegisterType((*HttpReq)(nil), "hall.base.HttpReq")
	proto.RegisterType((*HttpResp)(nil), "hall.base.HttpResp")
	proto.RegisterType((*EventReportNotify)(nil), "hall.base.EventReportNotify")
	proto.RegisterType((*LogonRegisterReq)(nil), "hall.base.LogonRegisterReq")
	proto.RegisterType((*LogonRegisterResp)(nil), "hall.base.LogonRegisterResp")
	proto.RegisterType((*LogonReq)(nil), "hall.base.LogonReq")
	proto.RegisterType((*LogonResp)(nil), "hall.base.LogonResp")
	proto.RegisterType((*LogonOkNotify)(nil), "hall.base.LogonOkNotify")
	proto.RegisterType((*QueryUserGameInfoReq)(nil), "hall.base.QueryUserGameInfoReq")
	proto.RegisterType((*QueryUserGameInfoResp)(nil), "hall.base.QueryUserGameInfoResp")
	proto.RegisterType((*QueryUsersGameInfoReq)(nil), "hall.base.QueryUsersGameInfoReq")
	proto.RegisterType((*UserGameInfo)(nil), "hall.base.UserGameInfo")
	proto.RegisterType((*QueryUsersGameInfoResp)(nil), "hall.base.QueryUsersGameInfoResp")
	proto.RegisterType((*CheckPlaceValidReq)(nil), "hall.base.CheckPlaceValidReq")
	proto.RegisterType((*CheckPlaceValidResp)(nil), "hall.base.CheckPlaceValidResp")
}

func init() { proto.RegisterFile("hall_base/hall_base.proto", fileDescriptor_80b3503d5242968b) }

var fileDescriptor_80b3503d5242968b = []byte{
	// 2232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0xcd, 0x8e, 0x1b, 0xc7,
	0xf1, 0x07, 0xc9, 0xe5, 0x92, 0x53, 0xfc, 0xd8, 0xdd, 0xb1, 0x2c, 0x8f, 0xbe, 0xfe, 0x92, 0xc6,
	0xd6, 0xdf, 0x16, 0x10, 0x28, 0xc9, 0x3a, 0x36, 0x60, 0xc7, 0x89, 0x22, 0xad, 0x1c, 0x6b, 0x01,
	0x41, 0x96, 0x67, 0x2d, 0x25, 0x39, 0x24, 0x83, 0x5e, 0x4e, 0x93, 0x3b, 0xd0, 0xb0, 0x7b, 0xb6,
	0xbb, 0xc9, 0x15, 0x2f, 0x01, 0xf2, 0x00, 0x01, 0xf2, 0x00, 0xc9, 0x25, 0x97, 0x9c, 0xf2, 0x36,
	0x39, 0xe4, 0x11, 0xf2, 0x06, 0xb9, 0x06, 0xd5, 0xd5, 0xf3, 0xc5, 0x25, 0x75, 0x49, 0x8c, 0x5c,
	0x72, 0xe2, 0xd4, 0xaf, 0xab, 0xbb, 0xab, 0xab, 0xaa, 0x7f, 0x5d, 0x45, 0xb8, 0x76, 0xc6, 0xb2,
	0x2c, 0x3e, 0x65, 0x9a, 0x7f, 0xbf, 0xfc, 0x7a, 0x90, 0x2b, 0x69, 0xa4, 0xef, 0x21, 0xf0, 0x00,
	0x81, 0xf0, 0x37, 0x30, 0xf8, 0x8a, 0xcd, 0xf9, 0xc9, 0x52, 0x1d, 0x8b, 0xa9, 0xf4, 0xaf, 0xc2,
	0xee, 0x99, 0xd4, 0x26, 0x4d, 0x82, 0xd6, 0x9d, 0xd6, 0x47, 0xdd, 0xc8, 0x49, 0xfe, 0x6d, 0x18,
	0x64, 0xa9, 0x36, 0x5c, 0xc4, 0xb9, 0x54, 0x26, 0x68, 0xdb, 0x41, 0x20, 0xe8, 0x85, 0x54, 0x06,
	0x27, 0xce, 0xd8, 0x9c, 0xa7, 0x49, 0xd0, 0xa1, 0x89, 0x24, 0x85, 0x0f, 0x61, 0x84, 0xeb, 0xbf,
	0xd4, 0x5c, 0xbd, 0x58, 0x64, 0x9a, 0xa3, 0xe2, 0x42, 0x73, 0x55, 0xed, 0x40, 0x12, 0xe2, 0x4a,
	0xca, 0x79, 0x9a, 0xb8, 0xc5, 0x9d, 0x14, 0x32, 0x18, 0x3d, 0x4a, 0x92, 0xd4, 0xa4, 0x82, 0x65,
	0x4f, 0x98, 0x61, 0xfe, 0x5d, 0x18, 0x4a, 0x95, 0xce, 0x50, 0x8e, 0x15, 0x3f, 0x77, 0xcb, 0x0c,
	0x0a, 0x2c, 0xe2, 0xe7, 0xbe, 0x0f, 0x3b, 0x09, 0x33, 0xcc, 0xae, 0x34, 0x8c, 0xec, 0xb7, 0x7f,
	0x0d, 0xfa, 0xf8, 0x1b, 0x67, 0x5c, 0x38, 0x13, 0x7b, 0x28, 0x3f, 0xe3, 0x22, 0xfc, 0x5d, 0x0b,
	0x46, 0xaf, 0x58, 0x96, 0x26, 0x47, 0x19, 0x17, 0x06, 0x17, 0xb8, 0x0d, 0x83, 0x49, 0x96, 0x72,
	0x61, 0x62, 0xb3, 0xca, 0xb9, 0xdb, 0x02, 0x08, 0xfa, 0x76, 0x95, 0xf3, 0xda, 0x71, 0xdb, 0xf5,
	0xe3, 0xae, 0xfb, 0xa9, 0xb3, 0xc9, 0x4f, 0xce, 0xc1, 0x3b, 0x75, 0x07, 0x87, 0x1f, 0xc0, 0xb8,
	0x6e, 0x82, 0xce, 0xf1, 0x10, 0x13, 0x99, 0x14, 0x9b, 0xdb, 0xef, 0xf0, 0x3e, 0xf4, 0x4f, 0x96,
	0xce, 0x91, 0xb7, 0x00, 0x4c, 0x3a, 0x79, 0x1d, 0x4f, 0xe4, 0x42, 0x18, 0xab, 0xd5, 0x89, 0x3c,
	0x44, 0x8e, 0x10, 0x08, 0x1f, 0x83, 0x87, 0x8e, 0x2f, 0x9d, 0xee, 0xcc, 0x6d, 0x35, 0xcc, 0x6d,
	0xae, 0xd1, 0x5e, 0x5f, 0xe3, 0x6f, 0x2d, 0x18, 0x7f, 0x29, 0x0c, 0x57, 0xb8, 0x52, 0xc4, 0xcf,
	0x5f, 0x1d, 0xbe, 0x2d, 0x7c, 0x1b, 0x1d, 0x52, 0x85, 0xb5, 0x53, 0x0f, 0xab, 0xf5, 0x03, 0x53,
	0x89, 0xf3, 0x83, 0x17, 0x39, 0xc9, 0x7f, 0x08, 0x63, 0x56, 0x84, 0x3b, 0xb6, 0x41, 0xec, 0xde,
	0x69, 0x7d, 0x34, 0x38, 0x0c, 0x1e, 0x94, 0x39, 0xfb, 0xa0, 0x91, 0x0f, 0xd1, 0x88, 0xad, 0xa7,
	0x47, 0xc2, 0x73, 0xa9, 0x53, 0x17, 0xbb, 0x5d, 0x4a, 0x0f, 0x87, 0x61, 0xf0, 0xc2, 0x3f, 0xb5,
	0xc0, 0xb7, 0xc7, 0x3a, 0xca, 0x16, 0xa7, 0xff, 0xd6, 0xd1, 0xbe, 0x93, 0x23, 0x84, 0x7f, 0x69,
	0xc1, 0x41, 0xe9, 0xf6, 0xaf, 0x5f, 0x3f, 0x97, 0x26, 0x9d, 0xae, 0xfe, 0x63, 0x9e, 0x0f, 0xa0,
	0x67, 0xd8, 0x69, 0xc6, 0x85, 0xb4, 0x76, 0x77, 0xa2, 0x42, 0xc4, 0x91, 0xc9, 0x19, 0x4b, 0x95,
	0x90, 0xd6, 0xe2, 0x6e, 0x54, 0x88, 0xb8, 0x16, 0x53, 0x9c, 0xa5, 0x89, 0x73, 0xa7, 0x93, 0xc2,
	0xdf, 0xb7, 0x60, 0xef, 0x19, 0x67, 0x4b, 0x8e, 0x96, 0xfe, 0xf7, 0xed, 0x0c, 0x7f, 0x0b, 0xe3,
	0x82, 0x6d, 0x34, 0x65, 0xfe, 0x0f, 0xa1, 0x8f, 0xfb, 0xc4, 0x7a, 0xa9, 0xac, 0x3d, 0x83, 0xc3,
	0xab, 0xb5, 0x30, 0xd4, 0xa8, 0x2f, 0xea, 0xcd, 0x48, 0xf0, 0x3f, 0x83, 0x01, 0x9a, 0xac, 0xe3,
	0x1c, 0x57, 0x08, 0xda, 0x77, 0x3a, 0x6b, 0xc1, 0x6b, 0x10, 0x5a, 0x04, 0x8b, 0x72, 0xb7, 0xf0,
	0xd7, 0x30, 0x8a, 0xa4, 0x9c, 0xe3, 0xa0, 0xbd, 0x41, 0xb5, 0xc3, 0xb5, 0xd6, 0xd3, 0xdf, 0x39,
	0xb4, 0x5d, 0x77, 0xa8, 0x7f, 0x13, 0x3c, 0x5c, 0x8e, 0xee, 0x23, 0xf9, 0xa3, 0x02, 0xc2, 0xb3,
	0x8a, 0x4c, 0xcb, 0xe5, 0x37, 0xde, 0xeb, 0x87, 0x30, 0xc6, 0x8d, 0xe2, 0x6a, 0xad, 0xcb, 0xa7,
	0x68, 0x18, 0x1a, 0x8d, 0x94, 0x13, 0x69, 0x27, 0x0d, 0x7b, 0x27, 0x86, 0x29, 0xd3, 0x8c, 0xeb,
	0xc6, 0xbd, 0xb6, 0x10, 0x77, 0x3d, 0x7e, 0x9d, 0x66, 0xfc, 0xaa, 0x0c, 0xd9, 0xb9, 0xd3, 0xa9,
	0x32, 0x24, 0xfc, 0x47, 0x07, 0xc6, 0x68, 0x02, 0x5d, 0x49, 0xbd, 0xc8, 0xcc, 0xd6, 0x64, 0xaa,
	0xa5, 0x40, 0xbb, 0x99, 0xaa, 0x77, 0x61, 0x88, 0xc7, 0x8b, 0xdd, 0x85, 0x77, 0x7b, 0x0f, 0x10,
	0x7b, 0x42, 0x10, 0x92, 0xb4, 0xcc, 0x92, 0x52, 0x83, 0xb2, 0x0b, 0x64, 0x96, 0x14, 0x0a, 0xc8,
	0x21, 0xe9, 0x74, 0x5a, 0x6a, 0x74, 0x69, 0x0d, 0xc4, 0x0a, 0x95, 0x7d, 0xe8, 0x4c, 0x16, 0xc6,
	0x5e, 0x87, 0x4e, 0x84, 0x9f, 0x88, 0x4c, 0x39, 0x0f, 0x7a, 0x84, 0x4c, 0x39, 0xf7, 0xaf, 0x40,
	0x97, 0xbf, 0x31, 0x8a, 0x05, 0x7d, 0x8b, 0x91, 0xe0, 0x5f, 0x87, 0xbe, 0x49, 0xe7, 0x7c, 0x22,
	0xb5, 0x09, 0x3c, 0x6b, 0x7b, 0x29, 0x23, 0x1f, 0x9f, 0xca, 0x85, 0x71, 0x7c, 0x0c, 0x14, 0x7f,
	0x44, 0x28, 0xdc, 0x37, 0xc0, 0xbb, 0x48, 0x85, 0x1b, 0x1d, 0xd0, 0xdc, 0x8b, 0x54, 0xd0, 0xe0,
	0x2d, 0x80, 0x4c, 0x6a, 0xed, 0x46, 0x87, 0x34, 0x17, 0x11, 0x1a, 0xbe, 0x07, 0x63, 0x6d, 0x98,
	0x48, 0xe4, 0x74, 0xea, 0x54, 0x46, 0x56, 0x65, 0x54, 0xa0, 0xa4, 0xf6, 0x3e, 0x8c, 0xe4, 0x74,
	0x9a, 0xa5, 0x82, 0x3b, 0xad, 0xb1, 0xd5, 0x1a, 0x3a, 0x90, 0x94, 0xfe, 0x0f, 0x80, 0xbf, 0xc9,
	0xb9, 0x4a, 0xb9, 0x98, 0xf0, 0x60, 0x8f, 0x1e, 0xb9, 0x0a, 0xf1, 0xef, 0xc0, 0x20, 0xcf, 0xd8,
	0x8a, 0xab, 0x8c, 0x2f, 0x79, 0x16, 0xec, 0x13, 0x05, 0xd7, 0xa0, 0xf0, 0xaf, 0x2d, 0x38, 0x88,
	0xf8, 0x54, 0x71, 0x7d, 0xd6, 0x8c, 0xf6, 0xc6, 0xdb, 0x52, 0x4b, 0xa5, 0x76, 0x33, 0x95, 0x7c,
	0xd8, 0x99, 0x66, 0x6c, 0xe6, 0xae, 0x8a, 0xfd, 0xf6, 0x3f, 0xa7, 0xfb, 0x1b, 0x2b, 0xbb, 0xa8,
	0xcd, 0xb1, 0xc1, 0xe1, 0xb5, 0x5a, 0xe6, 0x37, 0x73, 0x8c, 0x2e, 0x70, 0x65, 0x81, 0x4b, 0xf2,
	0x6e, 0xa3, 0x8c, 0xf9, 0x05, 0x1c, 0xe0, 0x7d, 0xf9, 0x9a, 0xbc, 0x50, 0xdd, 0x88, 0x8d, 0xc5,
	0x92, 0x0f, 0x3b, 0xb5, 0x2a, 0xc9, 0x7e, 0x37, 0x58, 0xae, 0x53, 0x2b, 0x6f, 0x3e, 0x85, 0xfe,
	0x53, 0x63, 0xf2, 0xa7, 0x9c, 0x25, 0x98, 0x2f, 0xd3, 0x94, 0x67, 0xb4, 0x9c, 0x17, 0x91, 0x80,
	0xe8, 0x92, 0x65, 0x0b, 0x6e, 0x97, 0xf3, 0x22, 0x12, 0xc2, 0x25, 0xf4, 0x70, 0x1e, 0x16, 0x2b,
	0xd7, 0xa1, 0xaf, 0xb9, 0x48, 0x6a, 0x95, 0x4a, 0x29, 0xfb, 0xf7, 0xa1, 0x7b, 0xc6, 0x59, 0xa2,
	0xdd, 0xfd, 0x7f, 0xa7, 0xe6, 0x85, 0x62, 0xdb, 0x88, 0x34, 0xd0, 0xea, 0x53, 0x99, 0xac, 0xac,
	0x2b, 0xbd, 0xc8, 0x7e, 0x63, 0x4e, 0x2f, 0x54, 0xe6, 0xde, 0x37, 0xfc, 0x0c, 0x0f, 0xc9, 0xde,
	0x6d, 0x15, 0x4a, 0xa3, 0xf4, 0xf2, 0xa8, 0xf4, 0x0a, 0x5f, 0xc2, 0xc1, 0x97, 0x4b, 0x5b, 0xd6,
	0xa0, 0x2b, 0x9c, 0xf3, 0xdc, 0xd2, 0xad, 0x72, 0xe9, 0xd2, 0x80, 0x76, 0xcd, 0x80, 0xfa, 0xd9,
	0x3a, 0xcd, 0xb3, 0x85, 0x7f, 0xee, 0xc3, 0xfe, 0x33, 0x39, 0x93, 0x22, 0xe2, 0x33, 0x2c, 0xb0,
	0x14, 0x3a, 0xe3, 0x26, 0x78, 0x93, 0x33, 0x26, 0x04, 0xcf, 0xca, 0xb0, 0x54, 0x00, 0xfa, 0x92,
	0xe5, 0x79, 0x49, 0x55, 0x24, 0xf8, 0xf7, 0x61, 0x9f, 0x8b, 0x89, 0x5a, 0xe5, 0x26, 0x4e, 0xf8,
	0x32, 0x9d, 0x14, 0x55, 0xac, 0x17, 0xed, 0x39, 0xfc, 0x89, 0x83, 0xb7, 0xbe, 0xf9, 0xf7, 0x60,
	0x5c, 0x2c, 0xe1, 0xc6, 0xbb, 0x76, 0x7c, 0xe4, 0xd0, 0xa7, 0xa4, 0x86, 0xc7, 0x59, 0x69, 0xc3,
	0xe7, 0xee, 0x25, 0xf5, 0xa2, 0x52, 0xae, 0x5b, 0x51, 0xea, 0xf4, 0x1a, 0x56, 0x9c, 0x14, 0xaa,
	0x3e, 0xec, 0xa4, 0x73, 0x9e, 0x5a, 0x5e, 0xf1, 0x22, 0xfb, 0x8d, 0x9c, 0x55, 0x4c, 0xb7, 0x63,
	0x9e, 0x1d, 0x1b, 0x38, 0xec, 0xf8, 0x92, 0x8a, 0x4e, 0x2d, 0xbf, 0xd4, 0x55, 0x74, 0xea, 0x7f,
	0x0f, 0xfc, 0xd2, 0x88, 0x74, 0x1e, 0x23, 0xd9, 0xb2, 0xcc, 0x52, 0x8d, 0x17, 0x15, 0xe6, 0x9d,
	0xa4, 0xf3, 0x13, 0x8b, 0x23, 0x91, 0x2e, 0xb9, 0x4a, 0xa7, 0xab, 0xd8, 0xe6, 0xc1, 0xd0, 0xaa,
	0x01, 0x41, 0x47, 0x98, 0x0d, 0xf7, 0x60, 0x9c, 0xc8, 0x0b, 0x91, 0x49, 0x96, 0xc4, 0x33, 0x25,
	0x17, 0x79, 0x41, 0x3a, 0x05, 0xfa, 0x15, 0x82, 0xfe, 0x7b, 0xd0, 0x93, 0x3a, 0x16, 0x6c, 0xce,
	0x1d, 0xdd, 0xec, 0x4a, 0xfd, 0x9c, 0xcd, 0x39, 0x12, 0x9e, 0xab, 0xc3, 0xd3, 0xdc, 0xf2, 0x8c,
	0x17, 0xf5, 0x09, 0x38, 0xce, 0x6b, 0x77, 0x75, 0x7f, 0xbd, 0xa8, 0xb5, 0x0d, 0x0f, 0x6d, 0x78,
	0x40, 0x39, 0x80, 0x08, 0x6d, 0x76, 0x1d, 0xfa, 0x65, 0x94, 0x7d, 0x5a, 0xb2, 0x90, 0xb1, 0x49,
	0xc0, 0xcb, 0x10, 0x63, 0x66, 0xbe, 0x63, 0xc7, 0x7a, 0x28, 0xbf, 0x54, 0x19, 0xa6, 0xce, 0xa9,
	0x62, 0x22, 0x09, 0x3e, 0xa6, 0x6b, 0x68, 0x05, 0x9c, 0x30, 0x97, 0x09, 0xcf, 0x62, 0x21, 0x83,
	0x1f, 0xd1, 0x04, 0x2b, 0x3f, 0x97, 0x68, 0x86, 0x5e, 0xe9, 0x38, 0x63, 0x62, 0xb6, 0xe0, 0xc1,
	0x27, 0x76, 0xd0, 0xd3, 0x2b, 0xfd, 0xcc, 0x02, 0x38, 0xcc, 0xf2, 0xbc, 0x18, 0xfe, 0x94, 0x86,
	0x59, 0x9e, 0xbb, 0xe1, 0x6b, 0xd0, 0x17, 0xdc, 0x95, 0xb0, 0x9f, 0xd1, 0x0b, 0x27, 0x38, 0xf5,
	0x1e, 0x1f, 0xc2, 0xde, 0x5c, 0x9e, 0xa6, 0x19, 0x8f, 0x27, 0x4c, 0xa9, 0x94, 0x2b, 0x1d, 0x7c,
	0x6e, 0xa7, 0x8f, 0x09, 0x3e, 0x72, 0xa8, 0x3f, 0x86, 0xb6, 0xd4, 0xc1, 0x8f, 0xed, 0xec, 0xb6,
	0xd4, 0xfe, 0xbb, 0xb0, 0x2b, 0x75, 0xbc, 0xe4, 0x2a, 0xf8, 0x82, 0xce, 0x20, 0xf5, 0x2b, 0xae,
	0x30, 0x8a, 0x73, 0x96, 0x0a, 0x5b, 0x26, 0xa5, 0x49, 0xf0, 0x13, 0xa2, 0xf3, 0x02, 0x3a, 0x26,
	0xaf, 0xa0, 0x43, 0x71, 0xe6, 0x4f, 0x9d, 0x57, 0x58, 0x96, 0xe1, 0xdc, 0xbb, 0x30, 0x54, 0x5c,
	0xcb, 0x6c, 0x61, 0x52, 0x29, 0xe2, 0x37, 0xc1, 0x43, 0xa2, 0xfa, 0x0a, 0xfb, 0xe5, 0x9a, 0xca,
	0x2a, 0xf8, 0xd9, 0xba, 0xca, 0xaf, 0x50, 0xa5, 0xb4, 0x00, 0x37, 0x79, 0x44, 0x89, 0x59, 0x60,
	0xb8, 0x11, 0xd2, 0x85, 0x99, 0x07, 0xdf, 0x38, 0xba, 0x30, 0x73, 0xff, 0x03, 0x18, 0x29, 0x3e,
	0x91, 0xf3, 0x39, 0x17, 0x89, 0xad, 0x10, 0x22, 0xba, 0x71, 0x0d, 0x30, 0xfc, 0x7b, 0x1b, 0x0e,
	0xd6, 0x48, 0x62, 0x0b, 0x73, 0xfd, 0x3f, 0xec, 0x99, 0xb3, 0x54, 0x25, 0x71, 0xce, 0x94, 0xa1,
	0x84, 0x26, 0x96, 0x18, 0x59, 0xf8, 0x05, 0x53, 0xc6, 0xe6, 0x74, 0x55, 0x92, 0x74, 0x1a, 0x25,
	0xc9, 0x0d, 0x2a, 0xdd, 0x28, 0x64, 0xd4, 0xdc, 0xf5, 0x11, 0xb0, 0x31, 0xbb, 0x01, 0x9e, 0xc0,
	0x46, 0xcb, 0xe6, 0x38, 0x51, 0x43, 0x1f, 0x01, 0x9b, 0xe5, 0xf5, 0xac, 0xdb, 0x6d, 0x66, 0xdd,
	0x6d, 0x18, 0xb0, 0x09, 0xd7, 0x3a, 0x36, 0xf2, 0x35, 0x17, 0x8e, 0x0f, 0xc0, 0x42, 0xdf, 0x22,
	0x62, 0x1b, 0x4e, 0x39, 0x4b, 0x85, 0x53, 0x20, 0x46, 0x00, 0x0b, 0x91, 0xc2, 0x75, 0xe8, 0x2f,
	0x44, 0x7a, 0xbe, 0xc0, 0x74, 0x27, 0x4e, 0x28, 0x65, 0x3f, 0x84, 0x91, 0xe0, 0x17, 0xb6, 0x4a,
	0x8c, 0xed, 0x33, 0x4a, 0x15, 0xc7, 0x40, 0xf0, 0x0b, 0x7c, 0x23, 0x7f, 0x8e, 0xaf, 0x69, 0x00,
	0xbd, 0xa2, 0x0c, 0x1a, 0xd0, 0xdb, 0xeb, 0xc4, 0xf0, 0x0f, 0x3d, 0xe8, 0x3b, 0xd7, 0x9e, 0x6f,
	0x2d, 0xd4, 0xae, 0x43, 0x3f, 0x67, 0x5a, 0x5f, 0x48, 0x95, 0x38, 0x62, 0x2f, 0xe5, 0x1a, 0x99,
	0x76, 0x1a, 0x64, 0x5a, 0x67, 0xc9, 0x9d, 0x35, 0x96, 0x2c, 0xa8, 0xaf, 0x5b, 0xa3, 0xbe, 0xfa,
	0x8d, 0xde, 0x5d, 0xbb, 0xd1, 0x15, 0x49, 0xf4, 0x1a, 0x24, 0xd1, 0x78, 0x27, 0xfa, 0xeb, 0xef,
	0x44, 0x00, 0x3d, 0xcb, 0x1e, 0xce, 0x67, 0xdd, 0xa8, 0x10, 0x71, 0x1e, 0xe6, 0xbe, 0x5e, 0xe2,
	0x51, 0xa1, 0xe2, 0x16, 0x0b, 0x94, 0xe5, 0xc8, 0xa0, 0x56, 0x8e, 0x34, 0x38, 0x6c, 0xb8, 0xc6,
	0x61, 0xf7, 0x60, 0x9c, 0xa1, 0x0b, 0xe3, 0x14, 0xfb, 0xbd, 0x25, 0xcb, 0x0a, 0x82, 0xb4, 0xe8,
	0xb1, 0x03, 0x6d, 0x01, 0x84, 0xd1, 0x4c, 0x13, 0x47, 0x90, 0x85, 0x88, 0xa5, 0xd8, 0x69, 0x26,
	0x27, 0xaf, 0xc9, 0x20, 0x57, 0x8a, 0x55, 0xc8, 0xff, 0x68, 0xeb, 0x3b, 0xa4, 0x2d, 0x5b, 0x71,
	0x63, 0xf0, 0xec, 0x71, 0x1f, 0x15, 0x15, 0xf7, 0x4c, 0x0a, 0x7b, 0xe0, 0x75, 0x56, 0x7b, 0x7c,
	0x99, 0xd5, 0x3e, 0x84, 0xbd, 0xc9, 0x42, 0x29, 0x2e, 0x4c, 0xa9, 0x75, 0x44, 0x3e, 0xa9, 0xc1,
	0xa8, 0x78, 0x0f, 0xc6, 0x56, 0xa3, 0xca, 0xd9, 0x27, 0x94, 0x27, 0x88, 0x1e, 0x15, 0x60, 0xf8,
	0xcf, 0x36, 0x78, 0xee, 0x4a, 0x6e, 0x61, 0xb9, 0xea, 0x9e, 0xb6, 0xb7, 0xb3, 0x57, 0xe7, 0x6d,
	0xec, 0xb5, 0xf3, 0x16, 0xf6, 0xea, 0xbe, 0x95, 0xbd, 0x76, 0x2f, 0xb1, 0x57, 0x9d, 0x9c, 0x7a,
	0x6b, 0xe4, 0xb4, 0x0f, 0x1d, 0xcd, 0xdf, 0xb8, 0xbb, 0x89, 0x9f, 0x75, 0x2a, 0xf2, 0x1a, 0x54,
	0x54, 0xbf, 0xaf, 0xd0, 0xbc, 0xaf, 0x9b, 0x6e, 0x64, 0xc5, 0x3b, 0xc3, 0x06, 0xef, 0xdc, 0x04,
	0x0f, 0x3b, 0x31, 0x6d, 0xd8, 0x9c, 0x0a, 0x15, 0xfb, 0x67, 0x98, 0x03, 0xe8, 0xe6, 0x8b, 0x24,
	0x3f, 0x93, 0x82, 0xca, 0x14, 0x2f, 0xaa, 0x80, 0x70, 0x09, 0x23, 0xeb, 0xf8, 0xf2, 0xef, 0x9a,
	0x1f, 0x00, 0xa5, 0x42, 0xf9, 0x1f, 0x65, 0xb3, 0xfa, 0x2e, 0x88, 0x33, 0xea, 0x67, 0x05, 0x85,
	0x7e, 0x5c, 0xa4, 0x93, 0xe2, 0x3a, 0xb7, 0xe1, 0x19, 0x1c, 0x5e, 0xb9, 0x3c, 0x45, 0xe7, 0x2e,
	0xc9, 0xf0, 0x33, 0xcc, 0xe1, 0xca, 0x37, 0x0b, 0xae, 0x56, 0x45, 0x4f, 0x63, 0xff, 0xca, 0xe0,
	0xe7, 0xd8, 0xc7, 0x19, 0xa6, 0x66, 0xdc, 0xc4, 0x0d, 0x5a, 0x1e, 0x12, 0xf8, 0xb2, 0x0c, 0xfa,
	0x7c, 0x15, 0x37, 0xf2, 0xa1, 0x3f, 0x5f, 0xbd, 0x5c, 0xff, 0xbf, 0xa6, 0xf9, 0x8f, 0xee, 0x1f,
	0xdb, 0xf0, 0xee, 0x86, 0x2d, 0xb7, 0xe4, 0xdb, 0x2d, 0x00, 0x23, 0x0d, 0xcb, 0x62, 0xec, 0x62,
	0xdd, 0x1e, 0x9e, 0x45, 0x1e, 0xcb, 0x85, 0xc1, 0xe4, 0xc1, 0x8e, 0xd6, 0x0e, 0xba, 0x7f, 0x65,
	0x2f, 0x52, 0x61, 0x87, 0x6e, 0x80, 0xed, 0x5e, 0x69, 0xcc, 0xbd, 0xa7, 0x08, 0xd8, 0xc1, 0xf7,
	0xa1, 0xec, 0x5b, 0x49, 0x81, 0xda, 0xb5, 0x61, 0x01, 0x5a, 0xa5, 0x66, 0x9b, 0xba, 0x7b, 0xa9,
	0x4d, 0xbd, 0x02, 0x5d, 0x3d, 0x91, 0x8a, 0xbb, 0xa7, 0x81, 0x04, 0xdc, 0x17, 0x83, 0x1e, 0xdb,
	0x06, 0xbd, 0x5f, 0x35, 0xe8, 0x47, 0xd8, 0xa0, 0xaf, 0x75, 0xb6, 0xde, 0xe5, 0xce, 0xf6, 0xb8,
	0xe6, 0x1d, 0x5d, 0x8f, 0xc8, 0xb6, 0xff, 0x4f, 0x02, 0xe8, 0x51, 0x04, 0xa8, 0x49, 0xeb, 0x46,
	0x85, 0x18, 0x7e, 0x01, 0xc3, 0xba, 0x8f, 0xb7, 0xbe, 0xb1, 0x57, 0xa0, 0x4b, 0xe6, 0xb8, 0xae,
	0x86, 0x0c, 0x99, 0xc0, 0xd5, 0x4d, 0x86, 0x6c, 0x89, 0xd3, 0x27, 0x74, 0xff, 0x75, 0x2a, 0xa6,
	0xd2, 0x35, 0x8b, 0xef, 0x6d, 0x68, 0x99, 0xed, 0x1a, 0x95, 0x66, 0x28, 0xc0, 0x3f, 0x3a, 0xe3,
	0x93, 0xd7, 0x2f, 0x32, 0x36, 0xe1, 0xf6, 0x0f, 0xec, 0xb7, 0x15, 0x03, 0x8d, 0x47, 0xb7, 0xbd,
	0xfe, 0xe8, 0xee, 0x43, 0x27, 0x63, 0xc6, 0xd5, 0x02, 0xf8, 0x69, 0x11, 0x29, 0x8a, 0xf6, 0x33,
	0x93, 0x22, 0xbc, 0x0f, 0xef, 0x5c, 0xda, 0x6f, 0xf3, 0x89, 0xfe, 0x15, 0x00, 0x00, 0xff, 0xff,
	0x6e, 0x3a, 0x09, 0x7a, 0x00, 0x19, 0x00, 0x00,
}
